/**
 * Isaacs and Partners
 * Consultation Summary
 *
 * Displays the result generated by the consultation
 * assessment layer without making unsupported legal
 * conclusions.
 */

export class ConsultationSummary {
    constructor(options = {}) {
        this.container =
            options.container || null;
    }

    render(summary = {}) {
        if (!this.container) {
            return "";
        }

        const outcome =
            summary.outcome ||
            "assessment_pending";

        const title =
            summary.title ||
            this._getOutcomeTitle(
                outcome
            );

        const description =
            summary.description ||
            this._getOutcomeDescription(
                outcome
            );

        const services =
            Array.isArray(
                summary.recommendedServices
            )
                ? summary.recommendedServices
                : [];

        const outstanding =
            Array.isArray(
                summary.outstandingDocuments
            )
                ? summary.outstandingDocuments
                : [];

        this.container.innerHTML = `
            <article
                class="consultation-summary"
                data-outcome="${this._escape(
                    outcome
                )}"
            >

                <header>
                    <h2>
                        ${this._escape(title)}
                    </h2>

                    <p>
                        ${this._escape(
                            description
                        )}
                    </p>
                </header>

                ${
                    services.length
                        ? `
                            <section>
                                <h3>
                                    Potential Services
                                </h3>

                                <ul>
                                    ${services
                                        .map(
                                            (service) =>
                                                `<li>${this._escape(
                                                    service
                                                )}</li>`
                                        )
                                        .join("")}
                                </ul>
                            </section>
                        `
                        : ""
                }

                ${
                    outstanding.length
                        ? `
                            <section>
                                <h3>
                                    Information / Documents
                                    Requiring Attention
                                </h3>

                                <ul>
                                    ${outstanding
                                        .map(
                                            (item) =>
                                                `<li>${this._escape(
                                                    item
                                                )}</li>`
                                        )
                                        .join("")}
                                </ul>
                            </section>
                        `
                        : ""
                }

                <section>
                    <h3>
                        Important Notice
                    </h3>

                    <p>
                        This is a preliminary assessment
                        based on the information supplied.
                        It does not constitute a final legal
                        opinion or guarantee of an application
                        outcome.
                    </p>
                </section>

            </article>
        `;

        return this.container.innerHTML;
    }

    _getOutcomeTitle(outcome) {
        switch (outcome) {
            case "potentially_eligible":
                return "Potentially Suitable for Further Assessment";

            case "documents_required":
                return "Further Information Required";

            case "consultation_required":
                return "Further Consultation Recommended";

            case "not_enough_information":
                return "Additional Information Required";

            default:
                return "Preliminary Consultation Assessment";
        }
    }

    _getOutcomeDescription(outcome) {
        switch (outcome) {
            case "potentially_eligible":
                return "The information supplied indicates that the matter may be suitable for further professional assessment.";

            case "documents_required":
                return "Additional documentation should be reviewed before a final recommendation can be made.";

            case "consultation_required":
                return "The matter should be reviewed by the appropriate professional before further action is taken.";

            case "not_enough_information":
                return "The information supplied is insufficient to complete a meaningful preliminary assessment.";

            default:
                return "The consultation information has been recorded for assessment.";
        }
    }

    _escape(value) {
        return String(value)
            .replaceAll("&", "&amp;")
            .replaceAll("<", "&lt;")
            .replaceAll(">", "&gt;")
            .replaceAll('"', "&quot;")
            .replaceAll("'", "&#039;");
    }
}

export default ConsultationSummary;
