import auth from "../auth/AuthService.js";import authGuard from "../auth/AuthGuard.js";import authConfig from "../auth/auth.config.js";import ImmigrationApplicationService from "../services/ImmigrationApplicationService.js";
class Controller{
 constructor(){this.api=new ImmigrationApplicationService();this.select=null;this.shell=null;this.empty=null;this.question=null;this.form=null;this.answer=null;this.status=null;this.pv=null;this.pb=null;this.docs=null;this.audit=null;this.pdf=null;this.state=null;this.loading=false}
 async init(){const gate=await authGuard.requireAuthentication();if(!gate?.allowed)return;this.select=document.querySelector("[data-application-matter]");this.shell=document.querySelector("[data-application-shell]");this.empty=document.querySelector("[data-application-empty]");this.question=document.querySelector("[data-question]");this.form=document.querySelector("[data-answer-form]");this.answer=document.querySelector("#application-answer");this.status=document.querySelector("[data-application-status]");this.pv=document.querySelector("[data-progress-value]");this.pb=document.querySelector("[data-progress-bar]");this.docs=document.querySelector("[data-document-checklist]");this.audit=document.querySelector("[data-answer-audit]");this.pdf=document.querySelector("[data-pdf-link]");await this.loadMatters();this.select.addEventListener("change",()=>this.load(this.select.value));this.form.addEventListener("submit",e=>this.submit(e));const id=new URLSearchParams(location.search).get("matterId");if(id&&[...this.select.options].some(o=>o.value===id)){this.select.value=id;await this.load(id)}}
 async loadMatters(){await auth.initialise();const token=auth.getToken();const q=new URLSearchParams({select:"id,reference_number,title,service_type",order:"updated_at.desc"});const r=await fetch(`${authConfig.supabase.url}/rest/v1/matters?${q}`,{headers:{apikey:authConfig.supabase.publishableKey,Authorization:`Bearer ${token}`,Accept:"application/json"}});if(!r.ok){this.select.replaceChildren(new Option("Select a matter",""));return}const rows=await r.json();this.select.replaceChildren(new Option("Select a matter",""));for(const m of rows||[])this.select.appendChild(new Option(`${m.reference_number||"Matter"} — ${m.title||m.service_type||""}`,m.id))}
 async load(id){if(!id){this.shell.hidden=true;this.empty.hidden=false;return}this.empty.hidden=true;this.shell.hidden=false;this.status.textContent="Loading Anthony's application state…";try{this.state=await this.api.snapshot(id);this.render()}catch(e){this.status.textContent=e.message||"Unable to load application."}}
 async submit(e){e.preventDefault();if(this.loading||!this.state?.intake?.current_question_key)return;const text=String(this.answer.value||"").trim();if(!text)return;this.loading=true;try{this.state=await this.api.answer({matter_id:this.state.intake.matter_id,question_key:this.state.intake.current_question_key,answer:text});this.answer.value="";this.render()}catch(err){this.status.textContent=err.message||"Unable to save answer."}finally{this.loading=false}}
 render(){const p=this.state.progress||{};const intake=this.state.intake||{};this.pv.textContent=`${p.overallPercent||0}%`;this.pb.style.width=`${p.overallPercent||0}%`;this.status.textContent=intake.status==="READY_FOR_DOCUMENT_REVIEW"?"Anthony has completed the intake questions. Remaining work is document and staff review.":"Anthony is collecting the next required answer.";const q=this.state.nextQuestion;if(q){this.question.textContent=q.prompt;this.form.hidden=false}else{this.question.textContent="Anthony has no further intake questions. Anthony will keep the application and evidence checklist ready for staff review.";this.form.hidden=true}this.docs.replaceChildren();for(const d of this.state.documents||[]){const row=document.createElement("p");const s=String(d.status||"OUTSTANDING").toUpperCase();row.textContent=`${["ON_FILE","VERIFIED","NOT_REQUIRED","PAID"].includes(s)?"✓":"☐"} ${d.label} — ${s.replaceAll("_"," ")}`;this.docs.appendChild(row)}this.audit.replaceChildren();for(const [k,v] of Object.entries(intake.answer_states||{})){const row=document.createElement("p");row.textContent=`${k} — ${String(v.status||"PENDING").replaceAll("_"," ")}`;this.audit.appendChild(row)}if(!this.audit.children.length)this.audit.appendChild(Object.assign(document.createElement("p"),{className:"ip-empty-state",textContent:"No answers recorded yet."}));if(this.state.latestDocument?.signedUrl){this.pdf.hidden=false;this.pdf.href=this.state.latestDocument.signedUrl}else this.pdf.hidden=true}
}
const controller=new Controller();if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>controller.init().catch(console.error));else controller.init().catch(console.error);
