import auth from "../auth/AuthService.js";
import AILiaisonRuntimeService from "../services/AILiaisonRuntimeService.js";
import clientPortalAccess from "../services/ClientPortalAccessService.js";

class ClientLiaisonWidget {
    constructor(){this.root=null;this.panel=null;this.list=null;this.form=null;this.input=null;this.button=null;this.runtime=new AILiaisonRuntimeService();this.conversation=null;this.chatId=null;this.loading=false;this.approved=false;this.pollTimer=null}
    async initialise(){this.root=document.querySelector("[data-ai-liaison-widget]");if(!this.root)return this;await auth.initialise();if(!auth.isAuthenticated())return this;const user=auth.getCurrentUser();if(!user?.id)return this;this.chatId=`portal:${user.id}`;await this.refreshAccess();if(!this.approved)return this;this.bind();await this.loadConversation();this.pollTimer=window.setInterval(()=>this.refreshConversation().catch(console.error),10000);window.addEventListener("beforeunload",()=>window.clearInterval(this.pollTimer));return this}
    async refreshAccess(){try{this.approved=(await clientPortalAccess.getStatus())==="APPROVED"}catch(error){console.error(error);this.approved=false}this.renderGate();this.updateMessagesNavigation()}
    renderGate(){const statusElement=this.root.querySelector("[data-ai-status]"),locked=this.root.querySelector("[data-ai-locked]"),chat=this.root.querySelector("[data-ai-chat]");this.root.dataset.access=this.approved?"approved":"pending";if(!this.approved){if(statusElement)statusElement.textContent="Your secure AI Liaison will become available after Isaacs & Partners approves your portal access.";if(locked)locked.hidden=false;if(chat)chat.hidden=true;return}if(statusElement)statusElement.textContent=this.stateText(this.conversation?.state);if(locked)locked.hidden=true;if(chat)chat.hidden=false}
    updateMessagesNavigation(){document.querySelectorAll("[data-client-messages-link]").forEach(link=>{if(this.approved){link.classList.remove("client-nav-link--locked");link.removeAttribute("aria-disabled");link.removeAttribute("tabindex");return}link.classList.add("client-nav-link--locked");link.setAttribute("aria-disabled","true");link.setAttribute("tabindex","-1");link.onclick=e=>e.preventDefault()})}
    bind(){this.panel=this.root.querySelector("[data-ai-chat]");this.list=this.root.querySelector("[data-ai-message-list]");this.form=this.root.querySelector("[data-ai-message-form]");this.input=this.form?.querySelector("textarea[name='message']");this.button=this.form?.querySelector("button[type='submit']");this.form?.addEventListener("submit",e=>this.send(e))}
    async loadConversation(){try{this.conversation=await this.runtime.getClientConversation({chatId:this.chatId,channel:"PORTAL"});if(!this.conversation){this.setListMessage("Hi! I am your AI Liaison. How can I assist you today?");this.renderGate();return}await this.refreshConversation()}catch(error){console.error(error);this.setListMessage("Your secure conversation could not be loaded. Please try again.")}}
    async refreshConversation(){if(!this.conversation)return;try{this.conversation=await this.runtime.getConversation(this.conversation.id);this.renderMessages(await this.runtime.listMessages(this.conversation.id));this.renderGate();this.setLoading(false)}catch(error){console.error(error)}}
    async send(event){event.preventDefault();if(this.loading||!this.approved)return;const body=String(this.input?.value||"").trim();if(!body)return;if(["AI_ESCALATED","HUMAN_ACTIVE"].includes(String(this.conversation?.state||"").toUpperCase())){this.setListMessage("Your enquiry is currently with an authorised team member.");return}this.setLoading(true);try{const result=await this.runtime.sendClientMessage({body,chatId:this.chatId,channel:"PORTAL"});this.conversation=result.conversation||this.conversation;this.input.value="";if(this.conversation?.id)await this.refreshConversation()}catch(error){console.error(error);this.setListMessage(error?.message||"Unable to send your message. Please try again.")}finally{this.setLoading(false)}}
    renderMessages(messages=[]){if(!this.list)return;this.list.replaceChildren();if(!messages.length){this.setListMessage("Hi! I am your AI Liaison. How can I assist you today?");return}messages.slice(-6).forEach(message=>{const item=document.createElement("article");item.className=`ai-widget-message ai-widget-message--${String(message.sender_type||"system").toLowerCase()}`;const header=document.createElement("div");header.className="ai-widget-message__header";const sender=document.createElement("strong");sender.textContent=this.senderLabel(message.sender_type);const time=document.createElement("time");time.textContent=this.formatTimestamp(message.created_at);header.append(sender,time);const body=document.createElement("p");body.textContent=message.body||"";item.append(header,body);this.list.appendChild(item)});this.list.scrollTop=this.list.scrollHeight}
    senderLabel(type){return({CLIENT:"You",AI:"AI Liaison",STAFF:"Isaacs & Partners",SUPER_ADMIN:"Super Admin",SYSTEM:"Isaacs & Partners"})[String(type||"").toUpperCase()]||"Isaacs & Partners"}
    stateText(state){return({AI_ACTIVE:"AI Liaison is active.",AI_ESCALATED:"Your enquiry is with an authorised team member for human review.",HUMAN_ACTIVE:"An authorised team member is handling this conversation.",HUMAN_RESOLVED:"Human review has been completed.",AI_RESUMED:"AI Liaison has resumed this conversation."})[String(state||"AI_ACTIVE").toUpperCase()]||"Secure AI Liaison is active."}
    formatTimestamp(value){if(!value)return"";const date=new Date(value);return Number.isNaN(date.getTime())?"":new Intl.DateTimeFormat("en-ZA",{timeStyle:"short"}).format(date)}
    setListMessage(message){if(!this.list)return;this.list.replaceChildren();const p=document.createElement("p");p.className="ai-widget-empty";p.textContent=message;this.list.appendChild(p)}
    setLoading(loading){this.loading=Boolean(loading);if(!this.button)return;this.button.disabled=this.loading||["AI_ESCALATED","HUMAN_ACTIVE"].includes(String(this.conversation?.state||"").toUpperCase());this.button.textContent=this.loading?"Sending…":"Send"}
}
const clientLiaisonWidget=new ClientLiaisonWidget();
if(typeof document!=="undefined"){const init=()=>clientLiaisonWidget.initialise().catch(console.error);if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init()}
export{ClientLiaisonWidget};export default clientLiaisonWidget;
