import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL");const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");const OPENWA_BASE_URL=Deno.env.get("OPENWA_BASE_URL")?.replace(/\/$/,"");const OPENWA_API_KEY=Deno.env.get("OPENWA_API_KEY");const OPENWA_SESSION_ID=Deno.env.get("OPENWA_SESSION_ID");const OPENWA_WEBHOOK_SECRET=Deno.env.get("OPENWA_WEBHOOK_SECRET");const OPENWA_WORKER_TOKEN=Deno.env.get("OPENWA_WORKER_TOKEN");
if(!SUPABASE_URL||!SERVICE_ROLE_KEY)throw new Error("Supabase worker configuration is incomplete.");
const supabase=createClient(SUPABASE_URL,SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});const MAX_ATTEMPTS=5;
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}})}
function clean(v:unknown,max=4096){return String(v??"").trim().slice(0,max)}
function normaliseChatId(v:unknown){return clean(v,255)}
function isDirectChat(chatId:string){const id=normaliseChatId(chatId).toLowerCase();if(!id)return false;if(id.endsWith("@g.us")||id.endsWith("@broadcast")||id.endsWith("@newsletter")||id==="status@broadcast")return false;return id.endsWith("@c.us")||id.endsWith("@lid")||/^\d{6,20}$/.test(id)}
function normalisePhone(v:unknown){const value=clean(v,64);if(!value||value.includes("@lid"))return null;return value.replace(/@c\.us$/i,"").replace(/\D/g,"")||null}
function timingSafeEqual(a:Uint8Array,b:Uint8Array){if(a.length!==b.length)return false;let r=0;for(let i=0;i<a.length;i++)r|=a[i]^b[i];return r===0}
async function verifySignature(raw:string,sig:string|null){if(!OPENWA_WEBHOOK_SECRET||!sig)return false;const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(OPENWA_WEBHOOK_SECRET),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const digest=new Uint8Array(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(raw)));const expected=`sha256=${Array.from(digest).map(b=>b.toString(16).padStart(2,"0")).join("")}`;return timingSafeEqual(new TextEncoder().encode(expected),new TextEncoder().encode(sig))}
async function processOutbound(){if(!OPENWA_BASE_URL||!OPENWA_API_KEY||!OPENWA_SESSION_ID)throw new Error("OpenWA outbound configuration is incomplete.");const {data:row,error}=await supabase.from("communication_outbox").select("*, communication_messages(*)").eq("status","QUEUED").lte("available_at",new Date().toISOString()).order("available_at",{ascending:true}).order("created_at",{ascending:true}).limit(1).maybeSingle();if(error)throw error;if(!row)return{processed:false,message:"No queued WhatsApp messages."};const message=row.communication_messages;const chatId=normaliseChatId(row.chat_id);if(!isDirectChat(chatId)){await supabase.from("communication_outbox").update({status:"FAILED",last_error:"Blocked: WhatsApp group/broadcast destinations are not permitted.",locked_at:null,updated_at:new Date().toISOString()}).eq("id",row.id);if(message?.id)await supabase.from("communication_messages").update({status:"FAILED",metadata:{...(message.metadata||{}),transport_blocked:"NON_DIRECT_WHATSAPP_DESTINATION"},updated_at:new Date().toISOString()}).eq("id",message.id);return{processed:false,blocked:true,reason:"NON_DIRECT_WHATSAPP_DESTINATION"};}
const attempts=Number(row.attempts||0)+1;const claim=await supabase.from("communication_outbox").update({status:"PROCESSING",attempts,locked_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",row.id).eq("status","QUEUED").select().maybeSingle();if(claim.error)throw claim.error;if(!claim.data)return{processed:false,message:"Message was claimed by another worker."};try{await supabase.from("communication_messages").update({status:"SENDING",openwa_session_id:OPENWA_SESSION_ID,updated_at:new Date().toISOString()}).eq("id",message.id);const response=await fetch(`${OPENWA_BASE_URL}/api/sessions/${encodeURIComponent(OPENWA_SESSION_ID)}/messages/send-text`,{method:"POST",headers:{"Content-Type":"application/json","X-API-Key":OPENWA_API_KEY},body:JSON.stringify({chatId,text:message.body})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`OpenWA HTTP ${response.status}: ${JSON.stringify(result).slice(0,1000)}`);const providerMessageId=result?.id||result?.messageId||result?.data?.id||null;await supabase.from("communication_messages").update({status:"SENT",openwa_session_id:OPENWA_SESSION_ID,openwa_message_id:providerMessageId,metadata:{...(message.metadata||{}),openwa_response:result},updated_at:new Date().toISOString()}).eq("id",message.id);await supabase.from("communication_outbox").update({status:"SENT",locked_at:null,updated_at:new Date().toISOString(),last_error:null}).eq("id",row.id);return{processed:true,messageId:message.id,openwaMessageId:providerMessageId};}catch(error){const errorMessage=error instanceof Error?error.message:String(error);const terminal=attempts>=MAX_ATTEMPTS;await supabase.from("communication_outbox").update({status:terminal?"FAILED":"QUEUED",available_at:new Date(Date.now()+Math.min(attempts*15000,300000)).toISOString(),locked_at:null,last_error:errorMessage.slice(0,2000),updated_at:new Date().toISOString()}).eq("id",row.id);await supabase.from("communication_messages").update({status:terminal?"FAILED":"QUEUED",metadata:{...(message.metadata||{}),last_transport_error:errorMessage},updated_at:new Date().toISOString()}).eq("id",message.id);throw error}}
async function invokeAi(payload:any){if(!OPENWA_WORKER_TOKEN)throw new Error("OpenWA worker token is not configured.");const response=await fetch(`${SUPABASE_URL}/functions/v1/ai-liaison-runtime`,{method:"POST",headers:{"Content-Type":"application/json","X-AI-Internal-Worker-Token":OPENWA_WORKER_TOKEN},body:JSON.stringify(payload)});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`AI liaison HTTP ${response.status}: ${JSON.stringify(result).slice(0,1500)}`);return result}
async function processWebhook(req:Request){const rawBody=await req.text();if(!(await verifySignature(rawBody,req.headers.get("X-OpenWA-Signature"))))return json({error:"Invalid webhook signature."},401);let payload:any;try{payload=JSON.parse(rawBody)}catch{return json({error:"Invalid JSON."},400)}const event=String(payload?.event||"");const data=payload?.data||{};const idempotencyKey=payload?.idempotencyKey||req.headers.get("X-OpenWA-Idempotency-Key")||null;
if(event==="message.received"){const chatId=normaliseChatId(data.from||data.chatId);if(!chatId)return json({received:true,ignored:true,reason:"Missing chat ID."});if(!isDirectChat(chatId))return json({received:true,ignored:true,reason:"GROUP_OR_BROADCAST_CHAT_BLOCKED"});const {data:contact}=await supabase.from("communication_contacts").select("id,user_id,phone_number,chat_id,is_active").eq("chat_id",chatId).eq("is_active",true).maybeSingle();const customerUserId=contact?.user_id||null;const phoneNumber=normalisePhone(data.from)||normalisePhone(contact?.phone_number);const whatsappName=clean(data.pushName||data.notifyName||data.senderName||data.contactName||"",255)||null;const body=clean(data.body,4096);if(!body)return json({received:true,ignored:true,reason:"EMPTY_MESSAGE"});if(idempotencyKey){const existing=await supabase.from("communication_messages").select("id").eq("idempotency_key",idempotencyKey).maybeSingle();if(existing.data)return json({received:true,duplicate:true});if(existing.error&&existing.error.code!=="PGRST116")throw existing.error}
const {data:inserted,error}=await supabase.from("communication_messages").insert({customer_user_id:customerUserId,channel:"WHATSAPP",direction:"INBOUND",phone_number:phoneNumber,chat_id:chatId,body,status:"RECEIVED",openwa_session_id:payload?.sessionId||OPENWA_SESSION_ID||null,openwa_message_id:data.id||null,idempotency_key:idempotencyKey,delivery_id:payload?.deliveryId||req.headers.get("X-OpenWA-Delivery-Id")||null,metadata:{openwa_event:payload,whatsapp_name:whatsappName}}).select("id").single();if(error){if(error.code==="23505")return json({received:true,duplicate:true});throw error}
let ai=null;try{ai=await invokeAi({...(customerUserId?{userId:customerUserId}:{}),contactId:contact?.id||null,channel:"WHATSAPP",chatId,phoneNumber,whatsappName,body,messageId:data.id||inserted.id});await supabase.from("communication_messages").update({status:"HANDLED",metadata:{openwa_event:payload,ai_runtime_invoked:true,whatsapp_name:whatsappName}}).eq("id",inserted.id)}catch(error){console.error("AI handling failed after inbound persistence",error);await supabase.from("communication_messages").update({metadata:{openwa_event:payload,ai_runtime_invoked:false,ai_runtime_error:String(error).slice(0,1500),whatsapp_name:whatsappName}}).eq("id",inserted.id)}return json({received:true,authenticatedClient:Boolean(customerUserId),aiRuntime:ai?"HANDLED":"FAILED_OR_NOT_RETURNED"})}
if(["message.sent","message.ack","message.failed"].includes(event)){const providerId=data.id||data.messageId||null;if(providerId){const status=event==="message.failed"?"FAILED":event==="message.ack"?mapAckStatus(data):"SENT";await supabase.from("communication_messages").update({status,metadata:{openwa_event:payload},updated_at:new Date().toISOString()}).eq("openwa_message_id",providerId)}}return json({received:true})}
function mapAckStatus(data:any){const value=String(data?.ack||data?.status||"").toLowerCase();if(value.includes("read"))return"READ";if(value.includes("deliver"))return"DELIVERED";return"SENT"}
Deno.serve(async req=>{if(req.method!=="POST")return json({error:"Method not allowed."},405);try{if(req.headers.get("X-OpenWA-Signature"))return await processWebhook(req);const token=req.headers.get("X-OpenWA-Worker-Token");if(!OPENWA_WORKER_TOKEN||token!==OPENWA_WORKER_TOKEN)return json({error:"Forbidden."},403);return json(await processOutbound())}catch(error){console.error("OpenWA communication worker failed",error);return json({error:"Communication worker failed."},500)}});
