const AIEvents = Object.freeze({
    STARTED: "AI_STARTED",
    COMPLETED: "AI_COMPLETED",
    FAILED: "AI_FAILED",

    ANALYSIS_STARTED:
        "AI_ANALYSIS_STARTED",

    ANALYSIS_COMPLETED:
        "AI_ANALYSIS_COMPLETED",

    CLASSIFICATION_COMPLETED:
        "AI_CLASSIFICATION_COMPLETED",

    DECISION_CREATED:
        "AI_DECISION_CREATED",

    RISK_DETECTED:
        "AI_RISK_DETECTED",

    COMPLIANCE_FLAGGED:
        "AI_COMPLIANCE_FLAGGED",

    ELIGIBILITY_COMPLETED:
        "AI_ELIGIBILITY_COMPLETED",

    RECOMMENDATION_CREATED:
        "AI_RECOMMENDATION_CREATED",

    HUMAN_REVIEW_REQUIRED:
        "AI_HUMAN_REVIEW_REQUIRED"
});

export default AIEvents;
