import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import AIProviderService from "https://raw.githubusercontent.com/maliq273/isaacs-and-partners-website/main/app/ai/providers/AIProviderService.js";
import { DHA1738_FORM,valueAt,setAt,normalizeAnswer,nextQuestion,buildProgress,getApplicationDefinition,nextQuestionFor,buildProgressFor } from "https://raw.githubusercontent.com/maliq273/isaacs-and-partners-website/main/app/immigration/ApplicationIntakeRegistry.js";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"",SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"",ANON_KEY=Deno.env.get("SUPABASE_ANON_KEY")||Deno.env.get("SUPABASE_PUBLISHABLE_KEY")||"",INTERNAL=Deno.env.get("OPENWA_WORKER_TOKEN")||"",ORIGIN=Deno.env.get("AI_LIAISON_ALLOWED_ORIGIN")||"https://www.isaacsandpartners.online";
const admin=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{autoRefreshToken:false,persistSession:false}});
const cors={"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"authorization,apikey,content-type,x-ai-internal-worker-token,x-openwa-worker-token","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Content-Type":"application/json"};
const json=(v:any,s=200)=>new Response(JSON.stringify(v),{status:s,headers:cors});const clean=(v:any,n=5000)=>String(v??"").trim().slice(0,n);
async function authenticate(req:Request,body:any){const internal=clean(req.headers.get("x-ai-internal-worker-token")||req.headers.get("x-openwa-worker-token"),512);if(internal){if(!INTERNAL||internal!==INTERNAL)throw new Error("Invalid internal worker credentials.");return{internal:true,userId:clean(body?.userId)||null};}const token=clean(req.headers.get("authorization")).replace(/^Bearer\s+/i,"");if(!token||!ANON_KEY)throw new Error("Authentication is required.");const caller=createClient(SUPABASE_URL,ANON_KEY,{global:{headers:{Authorization:"Bearer "+token}},auth:{autoRefreshToken:false,persistSession:false}});const u=await caller.auth.getUser(token);if(u.error||!u.data?.user?.id)throw new Error("Authenticated user could not be verified.");return{internal:false,userId:u.data.user.id};}
async function matterFor(id:string,userId:string|null,internal:boolean){const r=await admin.from("matters").select("*").eq("id",id).maybeSingle();if(r.error)throw r.error;if(!r.data)throw new Error("Matter not found.");if(internal)return r.data;if(r.data.individual_user_id===userId)return r.data;if(r.data.business_id){const b=await admin.from("businesses").select("id").eq("id",r.data.business_id).eq("owner_user_id",userId).maybeSingle();if(b.error)throw b.error;if(b.data)return r.data;}throw new Error("You are not authorised to access this matter.");}
function unwrapFacts(input:any,out:any={},prefix=""){for(const [k,v] of Object.entries(input||{})){const path=prefix?prefix+"."+k:k;if(v&&typeof v==="object"&&!Array.isArray(v)&&Object.prototype.hasOwnProperty.call(v,"value")){if(v.value!==null&&v.value!==undefined&&String(v.value)!=="")setAt(out,path,v.value);continue;}if(v&&typeof v==="object"&&!Array.isArray(v))unwrapFacts(v,out,path);else if(v!==null&&v!==undefined&&String(v)!=="")setAt(out,path,v);}return out;}
function resolveFormCode(matter:any,requested:string|null=null){
 const requestedCode=String(requested||"").trim().toUpperCase();
 if(requestedCode)return requestedCode==="DHA_1738"?"DHA-1738":requestedCode;
 const text=(String(matter?.service_type||"")+" "+String(matter?.application_type||"")+" "+String(matter?.title||"")).toUpperCase();
 if(/DHA[- ]?84|PORT OF ENTRY|TRANSIT VISA/.test(text))return "DHA-84";
 if(/DHA[- ]?1738|CRITICAL SKILLS|TEMPORARY RESIDENCE/.test(text))return "DHA-1738";
 if(/BI[- ]?947|PERMANENT RESIDENCE/.test(text))return "BI-947";
 if(/BI[- ]?1712A|SPOUSAL RELATIONSHIP/.test(text))return "BI-1712A";
 if(/DHA[- ]?49|NOTICE OF APPEAL|APPEAL/.test(text))return "DHA-49";
 if(/SECTION[- ]?22|ASYLUM SEEKER/.test(text))return "SECTION-22";
 if(/SECTION[- ]?24|REFUGEE STATUS/.test(text))return "SECTION-24";
 if(/WAIVER|WAIVE/.test(text))return "WAIVER";
 if(/UNDESIRAB/.test(text))return "UNDESIRABILITY-REVIEW";
 return null;
}
async function genericDocuments(form:any,matter:any){
 const checks:any=matter?.portal_metadata?.application_document_checks||{};
 const rows=await admin.from("client_documents").select("document_type,status").eq("matter_id",matter.id);
 if(rows.error)throw rows.error;
 const normal=(v:any)=>String(v||"").toLowerCase().replace(/[^a-z0-9]+/g,"");
 return (form?.documents||[]).map((d:any)=>{
   const direct=checks[d.key]||checks[d.label];
   const key=normal(d.key),label=normal(d.label);
   const found=(rows.data||[]).find((x:any)=>{const t=normal(x.document_type);return t===key||t===label||t.includes(key)||key.includes(t)||t.includes(label)||label.includes(t);});
   let status=direct?.not_required?"NOT_REQUIRED":direct?.present===true?"ON_FILE":found?(String(found.status||"").toUpperCase()==="APPROVED"?"VERIFIED":"ON_FILE"):"OUTSTANDING";
   return {key:d.key,label:d.label,supplier:d.supplier||"CLIENT",status,required:d.required!==false};
 });
}
async function seedAnswers(matter:any){const a:any={};unwrapFacts(matter?.portal_metadata?.application_answers||{},a);if(matter?.individual_user_id){const p=await admin.from("profiles").select("first_name,last_name,email,phone").eq("id",matter.individual_user_id).maybeSingle();if(p.data){if(p.data.first_name&&!valueAt(a,"identity.first_names"))setAt(a,"identity.first_names",p.data.first_name);if(p.data.last_name&&!valueAt(a,"identity.surname"))setAt(a,"identity.surname",p.data.last_name);if(p.data.email&&!valueAt(a,"contact.email"))setAt(a,"contact.email",p.data.email);if(p.data.phone&&!valueAt(a,"contact.phone"))setAt(a,"contact.phone",p.data.phone);}}const w=await admin.from("anthony_workflow_state").select("known_facts").eq("matter_id",matter.id).order("updated_at",{ascending:false}).limit(1).maybeSingle();if(w.data?.known_facts)unwrapFacts(w.data.known_facts,a);if(valueAt(a,"passport.number")&&!valueAt(a,"identity.passportNumber"))setAt(a,"identity.passportNumber",valueAt(a,"passport.number"));return a;}
async function documents(matter:any){const result:any[]=[];const rows=await admin.from("client_documents").select("document_type,status").eq("matter_id",matter.id);if(rows.error)throw rows.error;const map:any={passport_biodata:["passport","passport_biodata","passport_data"],passport_validity:["passport"],offer_employment:["employment_document","offer_of_employment","employer_letter"],qualification:["qualification","degree","academic_record"],saqa:["saqa"],professional_body:["professional_body"],professional_registration:["professional_registration"],proof_residence:["proof_of_address","proof_of_residence"],current_sa_status:["visa","permit","status_document"],police_clearance:["police_clearance"],medical_report:["medical_report","medical"],yellow_fever:["yellow_fever"],employer_undertakings:["employment_document","employer_undertaking"]};for(const d of DHA1738_FORM.documents){let status="OUTSTANDING";const found=(rows.data||[]).find(x=>map[d.key]?.includes(String(x.document_type||"").toLowerCase())&&String(x.status||"").toUpperCase()!=="REJECTED");if(found)status=String(found.status||"").toUpperCase()==="APPROVED"?"VERIFIED":"ON_FILE";result.push({key:d.key,label:d.label,clientAction:d.clientAction,status});}const w=await admin.from("anthony_workflow_state").select("known_facts").eq("matter_id",matter.id).order("updated_at",{ascending:false}).limit(1).maybeSingle();const explicit=w.data?.known_facts?._document_checks||{};for(const d of result){const v=explicit[d.label];if(v?.not_required)d.status="NOT_REQUIRED";else if(v?.present===true)d.status="ON_FILE";}const inv=await admin.from("invoices").select("amount_paid,status,paid_at").eq("matter_id",matter.id).order("created_at",{ascending:false}).limit(10);if(inv.error)throw inv.error;if((inv.data||[]).some(x=>Number(x.amount_paid||0)>0||String(x.status||"").toUpperCase()==="PAID"||x.paid_at)){const p=result.find(x=>x.key==="payment_proof");if(p)p.status="PAID";}return result;}
async function ensure(matter:any,userId:string|null,requestedFormCode:string|null=null){
 const formCode=resolveFormCode(matter,requestedFormCode); if(!formCode)throw new Error("Anthony could not determine the immigration workflow for this matter.");
 const form=getApplicationDefinition(formCode); if(!form)throw new Error("Immigration workflow is not registered: "+formCode);
 const q=await admin.from("immigration_application_intakes").select("*").eq("matter_id",matter.id).eq("form_code",formCode).maybeSingle();if(q.error)throw q.error;if(q.data)return q.data;
 const answers=await seedAnswers(matter),states:any={};for(const qn of form.questions){const v=valueAt(answers,qn.key);if(v)states[qn.key]={status:"ANSWERED",value:String(v),source:"EXISTING_MATTER_DATA",updatedAt:new Date().toISOString()};}
 const docs=formCode==="DHA-1738"?await documents(matter):genericDocuments(form,matter);
 const progress=formCode==="DHA-1738"?buildProgress(states,docs):buildProgressFor(formCode,states,docs),n=formCode==="DHA-1738"?nextQuestion(states):nextQuestionFor(formCode,states);
 const ins=await admin.from("immigration_application_intakes").insert({matter_id:matter.id,client_user_id:matter.individual_user_id||userId,form_code:formCode,form_version:form.version,status:progress.status,answers,answer_states:states,document_checklist:docs,progress,current_question_key:n?.key||null,last_interaction_at:new Date().toISOString(),created_by:userId}).select("*").single();if(ins.error)throw ins.error;return ins.data;
}
async function latestDocument(intake:any){if(!intake?.draft_document_id)return null;const d=await admin.from("immigration_application_documents").select("*").eq("id",intake.draft_document_id).maybeSingle();if(d.error)throw d.error;if(!d.data)return null;const s=await admin.storage.from("immigration-generated").createSignedUrl(d.data.generated_path,3600);return{...d.data,signedUrl:s.data?.signedUrl||null};}
async function generateDraft(intake:any,matter:any,userId:string|null){const formCode=String(intake.form_code||"").toUpperCase(),form=getApplicationDefinition(formCode);if(!form?.template&&formCode!=="DHA-1738")return null;const templateKey=formCode==="DHA-1738"?"DHA_1738":formCode.replace("-","_");const response=await fetch(SUPABASE_URL+"/functions/v1/immigration-document-engine",{method:"POST",headers:{"Content-Type":"application/json","x-ai-internal-worker-token":INTERNAL},body:JSON.stringify({action:"GENERATE_FORM",template:templateKey,answers:intake.answers||{},fieldMap:formCode==="DHA-1738"?DHA1738_FORM.fieldMap:{},metadata:{caseType:formCode,checklist:intake.document_checklist,source:"Anthony Isaacs / authoritative intake"},matter_id:matter.id,client_user_id:matter.individual_user_id||userId,actor:userId||"ANTHONY"})});const payload=await response.json().catch(()=>({}));if(!response.ok||!payload?.ok)throw new Error(payload?.error||"DHA-1738 draft generation failed.");if(intake.draft_document_id)await admin.from("immigration_application_documents").update({status:"SUPERSEDED",updated_at:new Date().toISOString()}).eq("id",intake.draft_document_id);const u=await admin.from("immigration_application_intakes").update({draft_document_id:payload.documentId,field_audit:payload.fieldAudit||{},updated_at:new Date().toISOString()}).eq("id",intake.id).select("*").single();if(u.error)throw u.error;return payload;}
async function snapshot(id:string,userId:string|null,internal:boolean,requestedFormCode:string|null=null){const matter=await matterFor(id,userId,internal);const formCode=resolveFormCode(matter,requestedFormCode);const form=getApplicationDefinition(formCode||"");if(!form)throw new Error("Immigration workflow is not registered for this matter.");let intake=await ensure(matter,userId,formCode);const docs=formCode==="DHA-1738"?await documents(matter):await await genericDocuments(form,matter),progress=formCode==="DHA-1738"?buildProgress(intake.answer_states||{},docs):buildProgressFor(formCode,intake.answer_states||{},docs),changed=JSON.stringify(docs)!==JSON.stringify(intake.document_checklist)||JSON.stringify(progress)!==JSON.stringify(intake.progress);if(changed){const u=await admin.from("immigration_application_intakes").update({document_checklist:docs,progress,status:progress.status,updated_at:new Date().toISOString()}).eq("id",intake.id).select("*").single();if(u.error)throw u.error;intake=u.data;}const next=formCode==="DHA-1738"?nextQuestion(intake.answer_states||{}):nextQuestionFor(formCode,intake.answer_states||{});return{ok:true,matter:{id:matter.id,reference_number:matter.reference_number,title:matter.title,service_type:matter.service_type},workflow:{code:formCode,mode:form.mode,populationStatus:form.populationStatus},intake,nextQuestion:next,documents:docs,progress:intake.progress,latestDocument:await latestDocument(intake)};}
async function parseWhatsApp(question:any,body:string){const p=new AIProviderService();if(!p.isConfigured())return normalizeAnswer(body);try{const r=await p.generate({temperature:0,maxOutputTokens:300,system:"You are Anthony Isaacs. Extract only the customer's direct answer to the current immigration application question. Return JSON only: {value:string}. Never invent.",user:JSON.stringify({question:question.prompt,answer:body})});const t=String(r?.text||"").trim(),a=t.indexOf("{"),b=t.lastIndexOf("}");if(a>=0&&b>a){const parsed=JSON.parse(t.slice(a,b+1));return normalizeAnswer(parsed.value);}}catch{}return normalizeAnswer(body);}
async function answer(body:any,userId:string|null,internal:boolean){const matter=await matterFor(clean(body.matter_id,80),userId,internal);let intake=await ensure(matter,userId,clean(body.form_code)||null);const form=getApplicationDefinition(intake.form_code);const key=clean(body.question_key)||intake.current_question_key;const q=form?.questions?.find((x:any)=>x.key===key);if(!q)throw new Error("Unknown immigration application question.");const normalized=body.not_applicable?{status:"NOT_APPLICABLE",value:"Not applicable"}:body.answer!==undefined?normalizeAnswer(body.answer):await parseWhatsApp(q,body.body||"");if(!normalized.value)throw new Error("Anthony needs an answer before moving to the next question.");const answers=JSON.parse(JSON.stringify(intake.answers||{})),states=JSON.parse(JSON.stringify(intake.answer_states||{}));setAt(answers,key,normalized.value);states[key]={status:normalized.status,value:normalized.value,source:internal?"WHATSAPP_ANTHONY":"PORTAL_ANTHONY",updatedAt:new Date().toISOString()};const docs=intake.form_code==="DHA-1738"?await documents(matter):genericDocuments(form,matter),progress=intake.form_code==="DHA-1738"?buildProgress(states,docs):buildProgressFor(intake.form_code,states,docs),n=intake.form_code==="DHA-1738"?nextQuestion(states):nextQuestionFor(intake.form_code,states),log=[...(intake.audit_log||[]),{at:new Date().toISOString(),question:key,status:normalized.status,source:internal?"WHATSAPP":"PORTAL",actor:userId||"ANTHONY"}].slice(-200);const u=await admin.from("immigration_application_intakes").update({answers,answer_states:states,document_checklist:docs,progress,status:progress.status,current_question_key:n?.key||null,last_interaction_at:new Date().toISOString(),audit_log:log,updated_at:new Date().toISOString()}).eq("id",intake.id).select("*").single();if(u.error)throw u.error;intake=u.data;let draft=null;try{draft=await generateDraft(intake,matter,userId);}catch(e){console.error("[immigration-application-runtime] draft generation",e);}const fresh=await admin.from("immigration_application_intakes").select("*").eq("id",intake.id).single();if(fresh.error)throw fresh.error;return{...(await snapshot(matter.id,userId,internal,intake.form_code)),draft};}
async function summary(id:string,userId:string|null,internal:boolean,formCode:string|null=null){const s=await snapshot(id,userId,internal,formCode),missing=s.documents.filter((x:any)=>x.status==="OUTSTANDING").map((x:any)=>x.label),lines=[String(s.workflow?.code||"IMMIGRATION")+" APPLICATION SUMMARY","Matter: "+(s.matter.reference_number||s.matter.id),"Progress: "+s.progress.overallPercent+"% (questions "+s.progress.questionsCompleted+"/"+s.progress.questionsTotal+"; documents "+s.progress.documentsCompleted+"/"+s.progress.documentsTotal+")","Status: "+s.intake.status,"Next question: "+(s.nextQuestion?.label||"None"),"Outstanding documents:",...(missing.length?missing.map((x:string)=>"☐ "+x):["☑ No checklist items currently outstanding."]),s.latestDocument?.signedUrl?"PDF: "+s.latestDocument.signedUrl:"PDF: No draft has been generated yet.","Field audit: "+(s.intake.field_audit?.filledCount||0)+" filled; "+(s.intake.field_audit?.notAvailableCount||0)+" not available; "+(s.intake.field_audit?.unmappedCount||0)+" unmapped; complete="+(s.intake.field_audit?.formPopulationComplete?"YES":"NO")+"."];
return{...s,summary:lines.join("\n")};}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const body=req.method==="POST"?await req.json():Object.fromEntries(new URL(req.url).searchParams.entries()),who=await authenticate(req,body),id=clean(body.matter_id);if(!id)throw new Error("matter_id is required.");const action=clean(body.action||"SNAPSHOT").toUpperCase();if(action==="SNAPSHOT")return json(await snapshot(id,who.userId,who.internal,clean(body.form_code)||null));if(action==="ANSWER")return json(await answer(body,who.userId,who.internal));if(action==="GENERATE"){const s=await snapshot(id,who.userId,who.internal),m=await matterFor(id,who.userId,who.internal),d=await generateDraft(s.intake,m,who.userId);return json({...s,draft:d});}if(action==="SUMMARY")return json(await summary(id,who.userId,who.internal,clean(body.form_code)||null));throw new Error("Unsupported action.");}catch(e){console.error("[immigration-application-runtime]",e);return json({error:e instanceof Error?e.message:"Immigration application runtime failed."},400)}});
