import ImmigrationInterviewEngine from "../immigration/ImmigrationInterviewEngine.js";
import AIProviderService from "./providers/AIProviderService.js";

const AUTHORITY_ROLES = new Set(["STAFF","SUPER_ADMIN","DIRECTOR","PARTNER","SHAREHOLDER","STAKEHOLDER"]);
const DOCUMENTS = Object.freeze({
  "identity.surname":"Passport biodata page","identity.first_names":"Passport biodata page","identity.date_of_birth":"Passport biodata page","identity.place_of_birth":"Passport biodata page","identity.nationality":"Passport biodata page","identity.gender":"Passport biodata page",
  "passport.number":"Passport biodata page","passport.issue_date":"Passport biodata page","passport.expiry_date":"Passport biodata page",
  "contact.email":"Client contact details / email confirmation","contact.phone":"Client contact details / WhatsApp confirmation",
  "residence.current_country":"Proof of current residence","residence.address":"Proof of residential address",
  "immigration.current_status":"Current South African visa / permit / status document","immigration.entry_date":"Passport entry stamp / travel history","immigration.previous_applications":"Previous South African visa / permit records","immigration.refusals":"Any refusal / cancellation / undesirable-person decision",
  "compliance.criminal_history":"Police clearance / criminal-history declaration where required",
  "employment.occupation":"Offer of employment / job description","employment.employer":"Offer of employment / employer letter","employment.job_title":"Offer of employment / job description","employment.start_date":"Offer of employment / employment contract","employment.salary":"Offer of employment / employment contract","employment.contract":"Signed employment contract","employment.labour_certificate":"Department of Employment and Labour certificate/recommendation where required","employment.work_location":"Offer of employment / employer letter",
  "qualifications.highest":"Highest relevant qualification certificate","qualifications.institution":"Qualification certificate / academic record","qualifications.experience":"CV and employment evidence","professional.registration":"Professional registration / proof of registration"
});
function clean(value,max=6000){return String(value??"").trim().slice(0,max)}
function getPath(obj,key){return key.split(".").reduce((v,k)=>v?.[k],obj)}
function setPath(obj,key,value){const parts=key.split(".");let target=obj;for(let i=0;i<parts.length-1;i++)target=target[parts[i]]??={};target[parts.at(-1)]={value:clean(value,1500),source:"ANTHONY_QUALIFICATION",status:"UNCONFIRMED"}}
function modeFor(identity){const role=String(identity?.authorityRole||"").toUpperCase();if(AUTHORITY_ROLES.has(role))return role==="STAFF"?"STAFF_FILE_CHECK":"SUPER_ADMIN_FILE_CHECK";return "CLIENT_DOCUMENT_REQUEST"}

export default class ImmigrationQualificationWorkflowService {
  constructor({db,provider=new AIProviderService()}={}){if(!db)throw new Error("ImmigrationQualificationWorkflowService requires a Supabase admin client.");this.db=db;this.provider=provider}
  async load({conversationId=null,matterId=null}={}){let q=this.db.from("anthony_workflow_state").select("*");if(matterId)q=q.eq("matter_id",matterId);else if(conversationId)q=q.eq("conversation_id",conversationId);else return null;const r=await q.order("updated_at",{ascending:false}).limit(1).maybeSingle();if(r.error)throw r.error;return r.data||null}
  async matter(matterId){if(!matterId)return null;const r=await this.db.from("matters").select("*").eq("id",matterId).maybeSingle();if(r.error)throw r.error;return r.data||null}
  async extractAnswer({question,body,mode}){if(!this.provider.isConfigured())return null;const result=await this.provider.generate({temperature:0,maxOutputTokens:900,system:"You are Anthony Isaacs, executive assistant and immigration workflow coordinator for Isaacs & Partners. Extract only information explicitly provided. Never invent facts. Return JSON only. Schema: {answers:[{key:string,value:string}],documentChecks:[{document:string,present:boolean}],paymentMention:string}. For staff or super-admin file checks, yes means the physical/file copy exists; it does not prove its content is accurate. Mode: "+mode,user:"Current question/checklist item: "+question+"\nUser message: "+body});if(!result?.text)return null;try{return JSON.parse(result.text.trim())}catch{return null}}
  checklistFor(workflow){const facts=workflow?.known_facts||{};const required=Array.isArray(workflow?.required_question_keys)?workflow.required_question_keys:[];return required.filter(key=>!getPath(facts,key)?.value).map(key=>({key,document:DOCUMENTS[key]||"Supporting evidence for this requirement"}))}
  async paymentStatus(matterId){const inv=await this.db.from("invoices").select("id,invoice_number,total,amount_paid,balance_due,status,payment_stage,paid_at").eq("matter_id",matterId).order("created_at",{ascending:false}).limit(5);if(inv.error)throw inv.error;const invoices=inv.data||[];if(!invoices.length)return {seen:false,invoices:[]};return {seen:invoices.some(x=>Number(x.amount_paid||0)>0||String(x.status||"").toUpperCase()==="PAID"||x.paid_at),invoices}}
  async save(workflow,patch){const r=await this.db.from("anthony_workflow_state").update({...patch,updated_at:new Date().toISOString()}).eq("id",workflow.id).select("*").single();if(r.error)throw r.error;return r.data}
  async phrase({mode,matter,checklist,missing,complete,payment}){const roleInstruction=mode==="CLIENT_DOCUMENT_REQUEST"?"Address the client directly. Ask them to upload the listed documents to the client portal or email them to Isaacs & Partners. Do not ask internal staff questions.":"Address the staff member/Super Admin as an internal file-check. Do not make them answer the client's immigration interview. Ask only whether the listed documents/information are on file, then explain what Anthony will obtain from the client.";
    const fallback=()=>{if(!complete){if(mode==="CLIENT_DOCUMENT_REQUEST")return "For "+(matter?.reference_number||"your matter")+", I still need the following from you:\n"+missing.slice(0,5).map(x=>"☐ "+x.document).join("\n")+"\n\nPlease upload these to the client portal or email them to Isaacs & Partners. I will continue the qualification as soon as they are received.";return "I am doing the internal file check for "+(matter?.reference_number||"this matter")+". Please confirm which of these are already on file:\n"+checklist.slice(0,8).map(x=>"☐ "+x.document).join("\n")+"\n\nI will compile what is already held, identify the remaining gaps, and obtain only the outstanding information/documents from the client."}if(payment.seen)return "The qualification/file check for "+(matter?.reference_number||"this matter")+" is complete. I can see a payment recorded against the matter, so I will proceed with the next authorised stage.";return "The qualification/file check for "+(matter?.reference_number||"this matter")+" is complete. I do not currently see a payment recorded against the matter. Please reach out to the client about payment; I will also send a reminder to the listed number."};
    if(!this.provider.isConfigured())return fallback();try{const result=await this.provider.generate({temperature:.2,maxOutputTokens:1100,system:"You are Anthony Isaacs, executive assistant and immigration portfolio coordinator at Isaacs & Partners. "+roleInstruction+" Use checkbox formatting. Never claim a payment exists unless the database result says seen=true. Never invent a document or fact. Be concise.",user:JSON.stringify({matter:matter?.reference_number,mode,checklist:checklist.slice(0,10),missing:missing.slice(0,10),complete,payment:{seen:payment.seen}})});return clean(result?.text)||fallback()}catch{return fallback()}}
  async process({identity,conversationId=null,matterId=null,body}={}){const workflow=await this.load({conversationId,matterId});if(!workflow||String(workflow.state||"").toUpperCase()!=="QUALIFICATION")return null;const matter=await this.matter(workflow.matter_id);const mode=modeFor(identity);const facts=JSON.parse(JSON.stringify(workflow.known_facts||{}));const caseType=matter?.service_type==="IMM-CRITICAL-SKILLS"?"critical_skills":matter?.service_type==="IMM-GENERAL"?"general_work":"temporary_residence";const engine=new ImmigrationInterviewEngine({caseType,answers:facts});const current=engine.getNextQuestions(1)[0]||null;const extracted=await this.extractAnswer({question:current?.q||"Internal document checklist",body,mode});let changed=false;
    for(const item of extracted?.answers||[]){if(item?.key&&item?.value){setPath(facts,item.key,item.value);changed=true}}
    const checks={...(facts._document_checks||{})};for(const item of extracted?.documentChecks||[]){if(item?.document)checks[item.document]={present:Boolean(item.present),source:mode}}facts._document_checks=checks;facts._last_actor_mode=mode;
    const updatedEngine=new ImmigrationInterviewEngine({caseType,answers:facts});const completeness=updatedEngine.completeness();const missing=updatedEngine.getNextQuestions(8).map(x=>({key:x.key,question:x.q,document:DOCUMENTS[x.key]||"Supporting evidence"}));const checklist=this.checklistFor({known_facts:facts,required_question_keys:workflow.required_question_keys});const complete=completeness.ready&&checklist.length===0;const payment=await this.paymentStatus(workflow.matter_id);const nextState=complete?"QUALIFICATION_COMPLETE":"QUALIFICATION";if(changed||JSON.stringify(workflow.known_facts||{})!==JSON.stringify(facts))await this.save(workflow,{known_facts:facts,state:nextState,application_completed_at:complete?new Date().toISOString():workflow.application_completed_at});const effectiveMissing=missing.length?missing:checklist;const reply=await this.phrase({mode,matter,checklist,missing:effectiveMissing,complete,payment});
    return {handled:true,action:"IMMIGRATION_QUALIFICATION",executed:true,mode,matter,workflow:{...workflow,state:nextState,known_facts:facts},completeness,checklist,missing:effectiveMissing,payment,complete,reply}}
}
