#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const CI = process.argv.includes('--ci') || process.env.CI === 'true';
const WRITE = process.argv.includes('--write') || CI;
const IGNORE = new Set(['.git','node_modules','dist','build','coverage','.next','.cache','reports']);
const TEXT = new Set(['.js','.mjs','.cjs','.ts','.tsx','.jsx','.html','.css','.json','.toml','.yml','.yaml','.sql']);
const SOURCE = new Set(['.js','.mjs','.cjs','.ts','.tsx','.jsx']);
const files=[]; const contents=new Map(); const findings=[];
const rel=f=>path.relative(ROOT,f).replaceAll(path.sep,'/');
const exists=f=>fs.existsSync(path.join(ROOT,f));
const add=(severity,subsystem,file,missing,risk,action,detail='')=>findings.push({severity,subsystem,file,missing,risk,action,detail});
const line=(text,index)=>text.slice(0,index).split(/\r?\n/).length;
function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(IGNORE.has(e.name))continue;const f=path.join(dir,e.name);if(e.isDirectory())walk(f);else if(TEXT.has(path.extname(e.name).toLowerCase())||e.name.startsWith('.env'))files.push(f)}}
function read(f){if(contents.has(f))return contents.get(f);try{const v=fs.readFileSync(f,'utf8');contents.set(f,v);return v}catch{return ''}}
function targetExists(target,from){const clean=target.split(/[?#]/)[0];if(!clean||/^(https?:|mailto:|tel:|javascript:|data:)/i.test(clean))return true;const base=clean.startsWith('/')?ROOT:path.dirname(from);const raw=path.resolve(base,clean.replace(/^\//,''));const c=[raw,raw+'.html',raw+'.js',raw+'.mjs',raw+'.css',raw+'.json',path.join(raw,'index.html'),path.join(raw,'index.js'),path.join(raw,'index.mjs')];return c.some(fs.existsSync)}
function stripComments(text){return text.replace(/\/\*[\s\S]*?\*\//g,'').replace(/(^|\s)\/\/.*$/gm,'$1')}

walk(ROOT); files.forEach(read);
let pkg={}; try{pkg=JSON.parse(read(path.join(ROOT,'package.json')))}catch{add('P0','CI/testing','package.json','Invalid or missing package.json','The project cannot be reliably installed.','Repair package.json.')}
if(!pkg.scripts?.test)add('P1','CI/testing','package.json','No npm test script','No standard automated test entry point exists.','Add automated tests.');
if(!pkg.scripts?.lint)add('P1','CI/testing','package.json','No lint script','Static regressions can reach main unnoticed.','Add lint/static analysis.');
if(!pkg.scripts?.['production-check'])add('P0','CI/testing','package.json','No production-check command','The repository cannot self-audit its production wiring.','Add the production-check command.');
if(!exists('.github/workflows/production-check.yml'))add('P0','CI/testing','.github/workflows/production-check.yml','No production-check workflow','Commits are not automatically audited.','Add the GitHub Actions gate.');
if(!exists('package-lock.json'))add('P1','CI/testing','package-lock.json','No npm lockfile','Dependency installation is not reproducible outside the CI-generated workspace.','Commit package-lock.json after npm install.');

const env=read(path.join(ROOT,'.env.example'));const declared=new Set([...env.matchAll(/^([A-Z][A-Z0-9_]+)=/gm)].map(m=>m[1]));
for(const [f,t] of contents){const name=rel(f);if(name.startsWith('scripts/')||name.endsWith('.md')||name.startsWith('cloudflare/'))continue;for(const m of t.matchAll(/(?:import\.meta\.env|process\.env)\.([A-Z][A-Z0-9_]+)/g))if(!declared.has(m[1]))add('P1','Environment',name,`Environment variable ${m[1]} is absent from .env.example`,'Deployment configuration can drift.','Document it in .env.example or remove the usage.',`Line ${line(t,m.index)}`)}

for(const [f,t] of contents){const name=rel(f);if(path.extname(f).toLowerCase()!=='.html'||name.startsWith('app/components/'))continue;for(const m of t.matchAll(/(?:src|href)=["']([^"'#?]+)["']/gi))if(!targetExists(m[1],f))add('P1','Frontend/assets',name,`Referenced target is missing: ${m[1]}`,'The browser can return 404 and lose UI functionality.','Fix the path or restore the target.',`Line ${line(t,m.index)}`)}

for(const [f,t] of contents){if(!SOURCE.has(path.extname(f).toLowerCase()))continue;const code=stripComments(t);for(const m of code.matchAll(/(?:from\s+|import\s*\(|export\s+[^;]*?from\s+)["']([^"']+)["']/g)){let spec=m[1];if(!spec.startsWith('.'))continue;spec=spec.split(/[?#]/)[0];const raw=path.resolve(path.dirname(f),spec);const c=[raw,...['.js','.mjs','.ts','.tsx','.jsx','.json'].map(x=>raw+x),...['index.js','index.mjs','index.ts','index.tsx'].map(x=>path.join(raw,x))];if(!c.some(fs.existsSync))add('P0','Module graph',rel(f),`Broken local import: ${m[1]}`,'The module cannot load at runtime.','Correct the import path or restore the module.',`Line ${line(t,m.index)}`)}}

const fnRoot=path.join(ROOT,'supabase/functions');const functions=fs.existsSync(fnRoot)?fs.readdirSync(fnRoot,{withFileTypes:true}).filter(e=>e.isDirectory()).map(e=>e.name).sort():[];for(const fn of functions)if(!fs.existsSync(path.join(fnRoot,fn,'index.ts')))add('P0','Supabase Edge Functions',`supabase/functions/${fn}`,'Missing index.ts entry point','The function cannot deploy from the repository.','Restore the entry point.');
for(const [f,t] of contents)for(const m of t.matchAll(/functions\.invoke\(\s*["'`]([^"'`]+)["'`]/g))if(!functions.includes(m[1]))add('P0','Frontend→Edge',rel(f),`Frontend invokes missing Edge Function: ${m[1]}`,'The runtime call will fail.','Create/deploy the function or correct the invoked name.',`Line ${line(t,m.index)}`);

for(const [f,t] of contents){const name=rel(f);if(name.startsWith('scripts/'))continue;const checks=[[/SUPABASE_SERVICE_ROLE_KEY\s*=\s*["'`][^"'`]+["'`]/g,'P0','Hard-coded Supabase service-role secret'],[/OPENWA_(?:API_KEY|WORKER_TOKEN|WEBHOOK_SECRET)\s*=\s*["'`][^"'`]+["'`]/g,'P0','Hard-coded OpenWA credential'],[/Authorization:\s*["'`]Bearer\s+[A-Za-z0-9._-]{20,}["'`]/g,'P0','Hard-coded bearer credential'],[/eval\s*\(/g,'P0','eval() usage'],[/dangerouslySetInnerHTML\s*:/g,'P2','dangerouslySetInnerHTML requires sanitisation review']];for(const [re,s,label] of checks)for(const m of t.matchAll(re))add(s,'Security',name,label,'Potential credential exposure or injection risk.','Review the specific usage and replace with safe behaviour where required.',`Line ${line(t,m.index)}`);for(const m of t.matchAll(/\.innerHTML\s*=\s*([^;\n]+)/g)){const rhs=m[1].trim();const staticLiteral=/^(?:["'](?:[^"'\\]|\\.)*["']|`(?:[^`\\]|\\.)*`)$/.test(rhs);if(!staticLiteral||rhs.includes('${'))add('P2','Security',name,'Dynamic innerHTML assignment requires XSS review','Untrusted or insufficiently constrained HTML may execute in the browser.','Prefer textContent/DOM construction or sanitise with a trusted allowlist.',`Line ${line(t,m.index)}`)}}

for(const [f,label] of [['app/auth/AuthService.js','Auth service'],['app/ai/AuthorityActionService.js','Authority action service'],['app/ai/CompanyTruthService.js','Company Truth'],['app/ai/HistoricalMemoryRetrievalService.js','Historical memory'],['app/ai/CustomerRelationshipMemoryEngine.js','Customer relationship memory'],['app/ai/RelationshipOperationalIntelligenceEngine.js','Operational intelligence'],['app/ai/AuthorityRoleIntelligenceEngine.js','Authority role intelligence'],['supabase/functions/ai-liaison-runtime/index.ts','AI liaison runtime'],['supabase/functions/openwa-communication-worker/index.ts','OpenWA communication worker']])if(!exists(f))add('P0','Architecture',f,`${label} is missing`,'A core production boundary is absent.',`Restore or replace ${label}.`);

// server.js and cloudflare/tunnel-config.yml are development/infrastructure tooling, not browser production source.
const severity={P0:0,P1:1,P2:2};findings.sort((a,b)=>(severity[a.severity]-severity[b.severity])||a.subsystem.localeCompare(b.subsystem)||a.file.localeCompare(b.file));const counts=findings.reduce((a,f)=>(a[f.severity]=(a[f.severity]||0)+1,a),{});const report={generatedAt:new Date().toISOString(),repository:'maliq273/isaacs-and-partners-website',branch:'main',filesScanned:files.length,sourceFilesScanned:[...contents].filter(([f])=>SOURCE.has(path.extname(f).toLowerCase())).length,edgeFunctions:functions,counts,findings};
const md=['# Isaacs & Partners — Production Check','',`Generated: ${report.generatedAt}`,'',`Files scanned: **${report.filesScanned}** | Source files: **${report.sourceFilesScanned}**`,'',`**P0:** ${counts.P0||0} | **P1:** ${counts.P1||0} | **P2:** ${counts.P2||0}`,'','| Severity | Subsystem | File | Missing / broken connection | Risk | Production action |','|---|---|---|---|---|---|',...findings.map(f=>`| ${f.severity} | ${f.subsystem} | \`${f.file}\` | ${f.missing.replaceAll('|','\\|')} | ${f.risk.replaceAll('|','\\|')} | ${f.action.replaceAll('|','\\|')} |`),'','> Static audit only. Live Supabase RLS, Edge Function, OpenWA, browser E2E, deployment, and secret/configuration tests remain required before production certification.',''].join('\n');
if(WRITE){fs.mkdirSync(path.join(ROOT,'reports'),{recursive:true});fs.writeFileSync(path.join(ROOT,'reports/production-check.json'),JSON.stringify(report,null,2));fs.writeFileSync(path.join(ROOT,'reports/production-check.md'),md)}
console.log(`Production check: ${report.filesScanned} files scanned; P0=${counts.P0||0} P1=${counts.P1||0} P2=${counts.P2||0}`);for(const f of findings)console.log(`[${f.severity}] ${f.subsystem} :: ${f.file} :: ${f.missing}`);if(CI&&((counts.P0||0)>0||(counts.P1||0)>0))process.exit(1);
