import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import WhatsAppAgent from "https://raw.githubusercontent.com/maliq273/isaacs-and-partners-website/main/app/communication/agents/WhatsAppAgent.js";
import AIProviderService from "https://raw.githubusercontent.com/maliq273/isaacs-and-partners-website/main/app/ai/providers/AIProviderService.js";
import CompanyTruthService from "https://raw.githubusercontent.com/maliq273/isaacs-and-partners-website/main/app/ai/CompanyTruthService.js";
import TruthFusionEngine from "https://raw.githubusercontent.com/maliq273/isaacs-and-partners-website/main/app/ai/TruthFusionEngine.js";
import HistoricalMemoryRetrievalService from "https://raw.githubusercontent.com/maliq273/isaacs-and-partners-website/main/app/ai/HistoricalMemoryRetrievalService.js";
import CustomerRelationshipMemoryEngine from "https://raw.githubusercontent.com/maliq273/isaacs-and-partners-website/main/app/ai/CustomerRelationshipMemoryEngine.js";
import RelationshipOperationalIntelligenceEngine from "https://raw.githubusercontent.com/maliq273/isaacs-and-partners-website/main/app/ai/RelationshipOperationalIntelligenceEngine.js";
import AuthorityRoleIntelligenceEngine from "https://raw.githubusercontent.com/maliq273/isaacs-and-partners-website/main/app/ai/AuthorityRoleIntelligenceEngine.js";
import IdentityRelationshipResolutionEngine from "https://raw.githubusercontent.com/maliq273/isaacs-and-partners-website/main/app/ai/IdentityRelationshipResolutionEngine.js";
import AnthonyAuthorizationEngine from "https://raw.githubusercontent.com/maliq273/isaacs-and-partners-website/main/app/ai/AnthonyAuthorizationEngine.js";
import AuthorityActionService from "https://raw.githubusercontent.com/maliq273/isaacs-and-partners-website/main/app/ai/AuthorityActionService.js";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL");
const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
const ANON_KEY=Deno.env.get("SUPABASE_ANON_KEY")??Deno.env.get("SUPABASE_PUBLISHABLE_KEY");
const INTERNAL_WORKER_TOKEN=Deno.env.get("OPENWA_WORKER_TOKEN");
const ALLOWED_ORIGIN=Deno.env.get("AI_LIAISON_ALLOWED_ORIGIN")??"https://www.isaacsandpartners.online";
if(!SUPABASE_URL||!SERVICE_ROLE_KEY)throw new Error("AI liaison runtime configuration is incomplete.");
const admin=createClient(SUPABASE_URL,SERVICE_ROLE_KEY,{auth:{autoRefreshToken:false,persistSession:false}});
const corsHeaders={"Access-Control-Allow-Origin":ALLOWED_ORIGIN,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-ai-internal-worker-token, x-openwa-worker-token","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
function json(b:any,s=200){return new Response(JSON.stringify(b),{status:s,headers:corsHeaders})}
function clean(v:any,m=4096){return String(v??"").trim().slice(0,m)}
function nullable(v:any,m=255){const t=clean(v,m);return t||null}
function channelOf(v:any){const c=clean(v,32).toUpperCase()||"PORTAL";if(!["PORTAL","WHATSAPP","EMAIL","OTHER"].includes(c))throw new Error("Invalid conversation channel.");return c}
function isDirectChat(id:string){const c=clean(id,255).toLowerCase();return !!c&&!c.endsWith("@g.us")&&!c.endsWith("@broadcast")&&!c.endsWith("@newsletter")&&c!=="status@broadcast"&&(c.endsWith("@c.us")||c.endsWith("@lid")||/^\d{6,20}$/.test(c))}
async function authenticate(req:Request,p:any){const it=clean(req.headers.get("X-AI-Internal-Worker-Token"),512)||clean(req.headers.get("X-OpenWA-Worker-Token"),512);if(it){if(!INTERNAL_WORKER_TOKEN||it!==INTERNAL_WORKER_TOKEN)throw new Response(JSON.stringify({error:"Invalid internal worker credentials."}),{status:401,headers:corsHeaders});const uid=clean(p?.userId,128);if(!uid)return{caller:admin,user:null,internal:true};const{data,error}=await admin.auth.admin.getUserById(uid);if(error||!data?.user?.id)throw new Response(JSON.stringify({error:"Internal client could not be resolved."}),{status:404,headers:corsHeaders});return{caller:admin,user:data.user,internal:true}}if(!ANON_KEY)throw new Response(JSON.stringify({error:"AI portal authentication is not configured."}),{status:503,headers:corsHeaders});const token=clean(req.headers.get("Authorization")).replace(/^Bearer\s+/i,"");if(!token)throw new Response(JSON.stringify({error:"Authentication is required."}),{status:401,headers:corsHeaders});const caller=createClient(SUPABASE_URL,ANON_KEY,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{autoRefreshToken:false,persistSession:false}});const{data,error}=await caller.auth.getUser(token);if(error||!data?.user?.id)throw new Response(JSON.stringify({error:"Authenticated user could not be verified."}),{status:401,headers:corsHeaders});return{caller,user:data.user,internal:false}}
async function matterFor(uid:string|null,mid:string|null,identity:any){if(!mid)return null;const{data,error}=await admin.from("matters").select("*").eq("id",mid).maybeSingle();if(error)throw error;if(!data)return null;const role=String(identity?.authorityRole||"").toUpperCase();if(role==="SUPER_ADMIN")return data;if(role==="STAFF"&&identity?.staff?.id){const a=await admin.from("assignments").select("matter_id,status").eq("staff_id",identity.staff.id).eq("matter_id",mid);if(a.error)throw a.error;if(a.data?.some((x:any)=>!x.status||!["COMPLETED","CANCELLED","CLOSED"].includes(String(x.status).toUpperCase())))return data;}if(uid&&data.individual_user_id===uid)return data;if(uid&&data.business_id){const r=await admin.from("businesses").select("id").eq("id",data.business_id).eq("owner_user_id",uid).maybeSingle();if(r.error)throw r.error;if(r.data)return data}throw new Error("You are not authorised to use this matter in the AI conversation.")}
async function conversation(uid:string|null,chatId:string,phone:string|null,channel:string,mid:string|null){const q=await admin.from("ai_conversations").select("*").eq("channel",channel).eq("chat_id",chatId).order("updated_at",{ascending:false}).limit(1).maybeSingle();if(q.error)throw q.error;if(q.data){if(q.data.client_user_id&&uid&&q.data.client_user_id!==uid)throw new Error("Conversation belongs to another user.");return q.data}const r=await admin.from("ai_conversations").insert({client_user_id:uid,matter_id:mid,chat_id:chatId,phone_number:phone,channel,state:"AI_ACTIVE",metadata:{source:"ai-liaison-runtime",created_by:"trusted-runtime"}}).select("*").single();if(r.error)throw r.error;return r.data}
async function history(cid:string){const r=await admin.from("ai_conversation_messages").select("id,direction,body,sender_type,metadata,created_at,intent,service_domain").eq("conversation_id",cid).order("created_at",{ascending:false}).limit(40);if(r.error)throw r.error;return(r.data||[]).reverse().map((x:any)=>({id:x.id,direction:x.direction,body:x.body,sender:x.sender_type,messageId:x.id,metadata:x.metadata||{},createdAt:x.created_at,intent:x.intent||null,serviceDomain:x.service_domain||null}))}
async function append(cid:string,sender:string,dir:string,body:string,intent:any,domain:any,metadata:any){const safeSender=["SUPER_ADMIN","STAFF","CLIENT","AI"].includes(String(sender||""))?sender:"CLIENT";const r=await admin.rpc("ai_append_conversation_message",{p_conversation_id:cid,p_sender_type:safeSender,p_direction:dir,p_body:body,p_intent:intent,p_service_domain:domain,p_metadata:{...(metadata||{}),identity_type:sender||"UNKNOWN"}});if(r.error)throw r.error;return r.data}
async function persistMemories(records:any[]){for(const record of records||[]){let q:any=admin.from("ai_customer_memories").select("id").eq("category",record.category).eq("memory_key",record.memory_key).eq("value_text",record.value_text).limit(1);if(record.contact_id)q=q.eq("contact_id",record.contact_id);else if(record.client_user_id)q=q.eq("client_user_id",record.client_user_id);else if(record.conversation_id)q=q.eq("conversation_id",record.conversation_id);const existing=await q.maybeSingle();if(existing.error&&existing.error.code!=="PGRST116")throw existing.error;if(existing.data?.id){const u=await admin.from("ai_customer_memories").update({last_confirmed_at:record.last_confirmed_at,last_seen_at:record.last_seen_at,status:"ACTIVE",evidence:record.evidence,source_message_id:record.source_message_id,metadata:record.metadata}).eq("id",existing.data.id);if(u.error)throw u.error}else{const ins=await admin.from("ai_customer_memories").insert(record);if(ins.error)throw ins.error}}}
async function queue(con:any,uid:string|null,body:string,phone:string|null,mid:string|null,source:string|null){if(!isDirectChat(con.chat_id))throw new Error("Outbound WhatsApp delivery is restricted to direct contacts.");const key=`ai-reply:${con.id}:${source||Date.now()}`;const ex=await admin.from("communication_messages").select("id").eq("idempotency_key",key).maybeSingle();if(ex.error&&ex.error.code!=="PGRST116")throw ex.error;if(ex.data?.id)return ex.data.id;const m=await admin.from("communication_messages").insert({customer_user_id:uid,matter_id:mid||con.matter_id||null,channel:"WHATSAPP",direction:"OUTBOUND",phone_number:phone||con.phone_number||null,chat_id:con.chat_id,body:body.slice(0,4096),status:"QUEUED",idempotency_key:key,metadata:{source:"ai-liaison-runtime",conversation_id:con.id,source_message_id:source}}).select("id").single();if(m.error)throw m.error;const o=await admin.from("communication_outbox").insert({message_id:m.data.id,session_id:null,chat_id:con.chat_id,status:"QUEUED"});if(o.error)throw o.error;return m.data.id}
async function scopeOperational(intelligence:any,identity:any){const role=String(identity?.authorityRole||"").toUpperCase();if(role==="SUPER_ADMIN")return intelligence;if(role!=="STAFF")return intelligence;const staffId=identity?.staff?.id;if(!staffId)return {...intelligence,matters:[],userMatters:[],appointments:[],allAppointments:[],documents:[],allDocuments:[],invoices:[],allInvoices:[],commitments:[],staffOwnership:[]};const a=await admin.from("assignments").select("matter_id,status").eq("staff_id",staffId);if(a.error)throw a.error;const ids=new Set((a.data||[]).filter((x:any)=>!x.status||!["COMPLETED","CANCELLED","CLOSED"].includes(String(x.status).toUpperCase())).map((x:any)=>x.matter_id));const f=(x:any)=>x?.matter_id&&ids.has(x.matter_id);return {...intelligence,matters:(intelligence.matters||[]).filter((x:any)=>ids.has(x.id)),userMatters:(intelligence.userMatters||[]).filter((x:any)=>ids.has(x.id)),appointments:(intelligence.appointments||[]).filter(f),allAppointments:(intelligence.allAppointments||[]).filter(f),documents:(intelligence.documents||[]).filter(f),allDocuments:(intelligence.allDocuments||[]).filter(f),invoices:(intelligence.invoices||[]).filter(f),allInvoices:(intelligence.allInvoices||[]).filter(f),commitments:(intelligence.commitments||[]).filter(f),staffOwnership:(intelligence.staffOwnership||[])} }
function agent(){const p=new AIProviderService();const c=new CompanyTruthService();return new WhatsAppAgent({db:admin,responseGenerator:async(input:any)=>{try{return await new TruthFusionEngine({provider:p,companyTruth:c}).generate(input)}catch(error){console.error("Anthony AI provider unavailable; using deterministic fallback",error);return null}}})}
const historicalRetriever=new HistoricalMemoryRetrievalService();const relationshipMemory=new CustomerRelationshipMemoryEngine();const roi=new RelationshipOperationalIntelligenceEngine({db:admin});const authorityEngine=new AuthorityRoleIntelligenceEngine({db:admin});const identityEngine=new IdentityRelationshipResolutionEngine({db:admin,authorityEngine});const authorisationEngine=new AnthonyAuthorizationEngine({db:admin});const actionService=new AuthorityActionService({db:admin});
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{status:200,headers:corsHeaders});if(req.method!=="POST")return json({error:"Method not allowed."},405);try{const p=await req.json();const{caller,user,internal}=await authenticate(req,p);const body=clean(p?.body);if(!body)return json({error:"Message body is required."},400);const channel=channelOf(p?.channel);if(internal&&channel!=="WHATSAPP")return json({error:"Internal worker requests are restricted to WhatsApp."},403);if(!internal&&channel!=="PORTAL")return json({error:"Browser AI requests are restricted to the client portal."},403);const chatId=nullable(p?.chatId,255)||(user?`portal:${user.id}`:"portal:unknown");const phone=nullable(p?.phoneNumber,64);const mid=nullable(p?.matterId,64);const msgId=nullable(p?.messageId,255);if(channel==="WHATSAPP"&&(!p?.chatId||!isDirectChat(chatId)))return json({error:"WhatsApp AI is restricted to direct contacts, not groups or broadcasts."},403);if(!internal&&chatId!==`portal:${user.id}`)return json({error:"Portal chat identity is server-controlled."},403);if(!internal){const a=await caller.rpc("client_portal_access_status");if(a.error)throw a.error;if(String(Array.isArray(a.data)?a.data[0]:a.data).toUpperCase()!=="APPROVED")return json({error:"Client portal access is not approved."},403)}
const identity=channel==="WHATSAPP"?await identityEngine.resolveWhatsApp({phoneNumber:phone,chatId,whatsappName:nullable(p?.whatsappName,255)}):null;const authorityRole=identity?.authorityRole||null;const staffConversation=Boolean(identity?.verified&&["STAFF","SUPER_ADMIN","DIRECTOR","PARTNER","SHAREHOLDER","STAKEHOLDER"].includes(String(authorityRole||"").toUpperCase()));const uid=identity?.userId||user?.id||identity?.contact?.user_id||null;const contact=identity?.contact||null;const matter=await matterFor(uid,mid,identity);const con=await conversation(uid,chatId,phone,channel,mid);const prior=await history(con.id);const authorization=authorisationEngine.evaluate({identity,message:body,intent:p?.intent,domain:p?.serviceDomain});const clientMsg=await append(con.id,identity?.identityType||"UNKNOWN","INBOUND",body,nullable(p?.intent,100),nullable(p?.serviceDomain,100),{source:"ai-liaison-runtime",transport:internal?"openwa":"portal",identity_type:identity?.identityType||"UNKNOWN",identity_status:identity?.identityStatus||"UNKNOWN",authority_id:identity?.authority?.authorityId||null,authority_role:authorityRole||null,phone_verified:Boolean(identity?.verified),relationship_count:identity?.relationships?.length||0,authorization_scope:authorization.scope.level,authorization_allowed:authorization.allowed,disclosure_rule:authorization.disclosureRule,...(msgId&&!staffConversation?{client_message_id:msgId}:{})});

async function notifySuperAdminWithAlert(adminDb:any,alertText:string,conversationId:string,customerPhone:string,chatId:string){
  const admins=await adminDb.from("authority_directory").select("user_id, phone_number, authority_role").eq("authority_role","SUPER_ADMIN").eq("is_active",true);
  if(admins.data&&admins.data.length>0){
    for(const adm of admins.data){
      const adminPhone=adm.phone_number;
      if(adminPhone){
        const adminChatId=adminPhone.includes("@")?adminPhone:`${adminPhone.replace(/[^0-9]/g,"")}@c.us`;
        const key=`sa-alert:${conversationId}:${adminPhone}`;
        const existing=await adminDb.from("communication_messages").select("id").eq("idempotency_key",key).maybeSingle();
        if(existing.data?.id)continue;
        const m=await adminDb.from("communication_messages").insert({customer_user_id:adm.user_id||null,channel:"WHATSAPP",direction:"OUTBOUND",phone_number:adminPhone,chat_id:adminChatId,body:alertText,status:"QUEUED",idempotency_key:key,metadata:{source:"ai-liaison-runtime",type:"SUPER_ADMIN_APPROVAL_ALERT",conversation_id:conversationId,customer_phone:customerPhone,customer_chat_id:chatId}}).select("id").single();
        if(m.data?.id)await adminDb.from("communication_outbox").insert({message_id:m.data.id,chat_id:adminChatId,status:"QUEUED"});
      }
    }
  }
}

// Lead Persistence for all incoming enquiries matched by WhatsApp / Phone Number
if(chatId||phone){const cleanPhone=phone||chatId.replace(/@.*$/,"");await admin.from("public_enquiries").upsert({session_id:chatId,service_domain:nullable(p?.serviceDomain,100),answers:[{message:body,timestamp:new Date().toISOString()}],qualified:true,metadata:{phone:cleanPhone,channel,chat_id:chatId,created_by:"ai-liaison-runtime"}},{onConflict:"session_id"}).catch(()=>null);}

// Super Admin Approval Decision Interceptor ("Can I proceed? YES or NO")
const cleanBody=body.trim().toLowerCase();
const isApproval=/^(yes|y|proceed|approve|approved|go ahead|ok|okay)$/i.test(cleanBody);
const isRejection=/^(no|n|reject|rejected|decline)$/i.test(cleanBody);
if((isApproval||isRejection)&&staffConversation&&String(authorityRole).toUpperCase()==="SUPER_ADMIN"){
  const pendingConv=await admin.from("ai_conversations").select("*").eq("state","approval_needed").order("updated_at",{ascending:false}).limit(1).maybeSingle();
  const targetConvId=pendingConv?.data?.id;

  if(targetConvId){
    if(isApproval){
      if(targetConvId){
        const cur=await admin.from("ai_conversations").select("facts").eq("id",targetConvId).single();
        await admin.from("ai_conversations").update({state:"AI_ACTIVE",facts:{...(cur.data?.facts||{}),approval_needed:false,super_admin_approved:true},updated_at:new Date().toISOString()}).eq("id",targetConvId);
      }
      const reply=`Thank you. Super Admin authorization CONFIRMED (YES) for customer ${pendingConv?.data?.phone_number||"enquiry"}. Anthony will proceed.`;
      const aiMsg=await append(con.id,"AI","OUTBOUND",reply,"SUPER_ADMIN_APPROVAL",null,{source:"ai-liaison-runtime"});
      const out=channel==="WHATSAPP"?await queue(con,uid,reply,phone,mid,msgId):null;
      return json({ok:true,conversation:con,message:clientMsg,aiMessage:aiMsg,transportMessageId:out,result:{action:"SUPER_ADMIN_APPROVED"}});
    }else{
      if(targetConvId){
        const cur=await admin.from("ai_conversations").select("facts").eq("id",targetConvId).single();
        await admin.from("ai_conversations").update({state:"HUMAN_ACTIVE",facts:{...(cur.data?.facts||{}),approval_needed:false,super_admin_rejected:true},updated_at:new Date().toISOString()}).eq("id",targetConvId);
      }
      const reply=`Understood. Super Admin authorization DECLINED (NO) for customer ${pendingConv?.data?.phone_number||"enquiry"}. Request assigned for manual human intervention.`;
      const aiMsg=await append(con.id,"AI","OUTBOUND",reply,"SUPER_ADMIN_DECLINED",null,{source:"ai-liaison-runtime"});
      const out=channel==="WHATSAPP"?await queue(con,uid,reply,phone,mid,msgId):null;
      return json({ok:true,conversation:con,message:clientMsg,aiMessage:aiMsg,transportMessageId:out,result:{action:"SUPER_ADMIN_DECLINED"}});
    }
  }
}

const action=await actionService.execute({identity,message:body,conversationId:con.id});const actionContext=action?.context||null;if(action.handled){const reply=clean(action.reply);const aiMsg=reply?await append(con.id,identity?.identityType||"UNKNOWN","OUTBOUND",reply,action.action||"AUTHORITY_ACTION",null,{source:"ai-liaison-runtime",runtime:"AuthorityActionService",assistant_name:"Anthony",authorization_scope:authorization.scope.level,authorization_allowed:authorization.allowed,action_executed:Boolean(action.executed)}):null;const out=reply&&channel==="WHATSAPP"?await queue(con,uid,reply,phone,mid,msgId):null;return json({ok:true,conversation:con,message:clientMsg,aiMessage:aiMsg,transportMessageId:out,result:{action:action.action||null,executed:Boolean(action.executed),permission:action.permission||null},context:{identity:{type:identity?.identityType,status:identity?.identityStatus,authorityRole,verified:identity?.verified},authorization}})}
if(!authorization.allowed&&(authorization.request.type!=="GENERAL")){const reply=`I recognise your database identity as ${String(identity?.identityType||"UNKNOWN").replace(/_/g," ")}${authorityRole?` with authority role ${authorityRole.replace(/_/g," ")}`:""}, but I cannot disclose or perform that request within the authority currently resolved for this WhatsApp number. ${authorization.reason}`;const aiMsg=await append(con.id,"AI","OUTBOUND",reply,"AUTHORIZATION_DENIED",null,{source:"ai-liaison-runtime",assistant_name:"Anthony",authorization_scope:authorization.scope.level,authorization_allowed:false,disclosure_rule:authorization.disclosureRule});const out=channel==="WHATSAPP"?await queue(con,uid,reply,phone,mid,msgId):null;return json({ok:true,conversation:con,message:clientMsg,aiMessage:aiMsg,transportMessageId:out,result:{action:"AUTHORIZATION_DENIED",reason:authorization.reason},context:{identity:{type:identity?.identityType,status:identity?.identityStatus,authorityRole,verified:identity?.verified},authorization}})}
if(["HUMAN_ACTIVE"].includes(String(con.state||"").toUpperCase())&&!staffConversation)return json({ok:true,conversation:con,message:clientMsg,aiMessage:null,result:{action:"ROUTE_TO_HUMAN",escalated:true},context:{historyLoaded:prior.length,maxHistory:40,identity:identity?{type:identity.identityType,status:identity.identityStatus,authorityRole,verified:identity.verified}:null,authorization}});
const historicalMemory=!staffConversation?await historicalRetriever.retrieve({db:admin,conversationId:con.id,contactId:contact?.id||null,userId:uid,query:body,history:prior}):{found:false,records:[],isHistoricalRecall:false};const relationshipRecords=!staffConversation?relationshipMemory.observe({body,contact,onboardingFacts:contact?.onboarding_facts||{},user,conversationId:con.id,sourceMessageId:clientMsg?.id||null}).records:[];await persistMemories(relationshipRecords);const rawOperational=await roi.build({contactId:contact?.id||null,userId:uid,matterId:mid});const operationalIntelligence=await scopeOperational(rawOperational,identity);
const ctx={id:con.id,chatId,phoneNumber:con.phone_number||phone,state:con.state||"AI_ACTIVE",facts:con.facts||{},memory:con.facts?.customerMemory||{},lastIntent:con.last_intent||null,lastService:con.last_service||null,messages:prior};let result:any;if(identity?.verified&&/^(?:hi[,.]?\s*)?(?:who am i|identify me|what is my identity|what identity do you have for me)\??$/i.test(body)){result={handled:true,action:"RESPOND",intent:{intent:"IDENTITY_AUTHORITY",confidence:1},servicePlan:{domain:null,service:null,commercial:{quoteRequired:false}},reply:`Hello ${identity.authoritativeName||"there"}. I recognise this WhatsApp number in the Isaacs & Partners database as ${String(identity.identityType||"UNKNOWN").replace(/_/g," ")}${authorityRole?` with authority role ${authorityRole.replace(/_/g," ")}`:""}. The identity resolution used the verified WhatsApp number and existing organisational/client records; your WhatsApp display name does not grant authority.`,aiProvider:"DETERMINISTIC_IDENTITY",aiModel:null,companySources:[identity.source||"database"]};}else result=await agent().handleInbound({chatId,phoneNumber:ctx.phoneNumber,body,messageId:msgId,user:staffConversation?null:user,matter,operationalContext:{...operationalIntelligence,authorityContext:identity?.authority||null,identityContext:identity,authorizationContext:authorization,assistantName:"Anthony"},conversation:ctx,contact,historicalMemory});

const isApprovalNeeded=Boolean(result?.requiresApproval||result?.action==="ESCALATE"||result?.context?.facts?.approval_needed);
const nextState=isApprovalNeeded?"approval_needed":(result?.action==="ESCALATE"&&!staffConversation?"AI_ESCALATED":con.state||"AI_ACTIVE");

if(result?.action==="ESCALATE"&&!staffConversation){const intervention=await admin.rpc("ai_create_human_intervention",{p_conversation_id:con.id,p_matter_id:mid||con.matter_id||null,p_client_user_id:uid,p_reason:result?.reason||"Anthony has requested authorised human assistance.",p_priority:result?.priority||"NORMAL",p_question:body,p_ai_context:{assistant_name:"Anthony",identity:identity?{type:identity.identityType,status:identity.identityStatus,authority_role:authorityRole}:null,authorization,operational:operationalIntelligence.portfolio||null}});if(intervention.error)throw intervention.error;}
const reply=clean(result?.reply,8192);const aiMsg=reply?await append(con.id,"AI","OUTBOUND",reply,result?.intent?.intent||null,result?.servicePlan?.domain||null,{source:"ai-liaison-runtime",runtime:"WhatsAppAgent",assistant_name:"Anthony",action:result?.action||"RESPOND",ai_provider:result?.aiProvider||null,ai_model:result?.aiModel||null,company_truth_sources:result?.companySources||[],context_messages_loaded:prior.length,historical_memory_found:historicalMemory.found,portfolio_attention:operationalIntelligence.portfolio.attentionLevel,next_action:operationalIntelligence.portfolio.nextAction,identity_type:identity?.identityType||"UNKNOWN",identity_status:identity?.identityStatus||"UNKNOWN",authority_id:identity?.authority?.authorityId||null,authority_role:authorityRole||null,phone_verified:Boolean(identity?.verified),authorization_scope:authorization.scope.level,authorization_allowed:authorization.allowed,disclosure_rule:authorization.disclosureRule}):null;
const facts={...(con.facts||{}),...(result?.context?.facts||{}),approval_needed:isApprovalNeeded,customerMemory:result?.context?.memory||con.facts?.customerMemory||{}};
await admin.from("ai_conversations").update({facts,last_intent:result?.intent?.intent||con.last_intent||null,last_service:result?.servicePlan?.service?.name||con.last_service||null,state:nextState,updated_at:new Date().toISOString()}).eq("id",con.id);

if(isApprovalNeeded&&!staffConversation){
  const customerPhone=phone||con.phone_number||chatId.replace(/@.*$/,"");
  const transcriptLines=[...prior.map((x:any)=>`${x.sender_type||x.sender||"CLIENT"}: ${x.body}`),`CLIENT: ${body}`];
  const transcript=transcriptLines.join("\n");
  const alertText=`⚠️ APPROVAL NEEDED FOR ANTHONY AI\n\nCustomer Phone: ${customerPhone}\n\nFull Conversation Transcript:\n${transcript.slice(-3000)}\n\nProposed Response / Action:\n"${reply||"Human Verification Required"}"\n\nCan I proceed? (Reply YES or NO)`;
  await notifySuperAdminWithAlert(admin,alertText,con.id,customerPhone,chatId);
}

let out=null;if(reply&&channel==="WHATSAPP"&&(result?.action==="RESPOND"||staffConversation))out=await queue(con,uid,reply,phone,mid,msgId);return json({ok:true,conversation:{...con,state:nextState,facts},message:clientMsg,aiMessage:aiMsg,transportMessageId:out,result:{action:result?.action||null,intent:result?.intent||null,servicePlan:result?.servicePlan||null,sales:result?.sales||null,escalated:result?.action==="ESCALATE",approvalNeeded:isApprovalNeeded,aiProvider:result?.aiProvider||null,aiModel:result?.aiModel||null,companySources:result?.companySources||[]},context:{historyLoaded:prior.length,maxHistory:40,historicalMemoryFound:historicalMemory.found,historicalRecall:historicalMemory.isHistoricalRecall,portfolio:operationalIntelligence.portfolio,identity:identity?{type:identity.identityType,status:identity.identityStatus,authorityRole,verified:identity.verified,source:identity.source,relationships:identity.relationships}:null,authorization}})}catch(e){if(e instanceof Response)return e;console.error("AI liaison runtime failed",e);return json({error:e instanceof Error?e.message:"AI liaison runtime failed."},500)}});
