-- Payroll configuration, employee components, per-payslip billing and versioned BRS 25.3.0 dictionary.
-- Applied to the live Supabase schema through the Supabase MCP; this file records the production schema change.

create table if not exists public.hr_payroll_profiles (id uuid primary key default gen_random_uuid(),business_id uuid not null unique references public.businesses(id) on delete cascade,billing_model text not null default 'PER_EMPLOYEE_PAYSLIP',payslip_unit_price numeric(12,2) not null default 0,currency text not null default 'ZAR',pay_frequency text not null default 'MONTHLY',bargaining_council_code text,bargaining_council_name text,bargaining_council_config jsonb not null default '{}'::jsonb,payroll_policy jsonb not null default '{}'::jsonb,sars_rules_version text not null default '25.3.0',active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.hr_payroll_components (id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,employee_id uuid references public.hr_employees(id) on delete cascade,component_code text not null,component_name text not null,component_type text not null check(component_type in ('EARNING','ALLOWANCE','FRINGE_BENEFIT','DEDUCTION','EMPLOYER_CONTRIBUTION','TAX_CREDIT','LUMP_SUM')),amount numeric(14,2) not null default 0,taxable boolean not null default false,pensionable boolean not null default false,uif_applicable boolean not null default false,sdl_applicable boolean not null default false,eti_applicable boolean not null default false,sars_source_code text,effective_from date,effective_to date,configuration jsonb not null default '{}'::jsonb,active boolean not null default true,created_at timestamptz not null default now());
create index if not exists hr_payroll_components_employee_idx on public.hr_payroll_components(employee_id,active);
create table if not exists public.hr_payslip_charge_events (id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete restrict,payroll_profile_id uuid references public.hr_payroll_profiles(id) on delete restrict,payroll_run_id uuid references public.hr_payroll_runs(id) on delete restrict,payroll_entry_id uuid references public.hr_payroll_entries(id) on delete restrict,employee_id uuid references public.hr_employees(id) on delete restrict,unit_price numeric(12,2) not null,quantity integer not null default 1 check(quantity=1),currency text not null default 'ZAR',status text not null default 'BILLABLE' check(status in ('BILLABLE','INVOICED','WAIVED','VOID')),source text not null default 'PAYSLIP_GENERATION',created_at timestamptz not null default now());
create unique index if not exists hr_payslip_charge_once on public.hr_payslip_charge_events(payroll_entry_id) where status <> 'VOID';
create table if not exists public.sars_brs2530_source_code_dictionary (code text primary key,family text not null,name text not null,data_type text not null,length_spec text,mandatory_rule text,conditional_rule text,version text not null default '25.3.0',introduced_yoa integer,retired_yoa integer,is_subcode boolean not null default false,foreign_service_code text,cents_required boolean not null default false,notes text);
create table if not exists public.sars_brs2530_validation_rules (id uuid primary key default gen_random_uuid(),rule_key text not null,code text,rule_type text not null,severity text not null default 'ERROR' check(severity in ('ERROR','WARNING','INFO')),expression jsonb not null,message text not null,version text not null default '25.3.0',effective_from date not null default '2026-03-01',active boolean not null default true,unique(rule_key,version));

alter table public.hr_payroll_profiles enable row level security;
alter table public.hr_payroll_components enable row level security;
alter table public.hr_payslip_charge_events enable row level security;
alter table public.sars_brs2530_source_code_dictionary enable row level security;
alter table public.sars_brs2530_validation_rules enable row level security;

-- Policies are created idempotently in the live hardening pass.
