import auth from "../auth/AuthService.js";
import authConfig from "../auth/auth.config.js";
import adminAccountsData from "./AdminAccountsDataService.js";
import adminBrandAssetService from "./AdminBrandAssetService.js";
import { resolveUserDashboardRole } from "./DashboardAccess.js";

const esc = value => String(value ?? "").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");

class AdminAccountsController {
    constructor(){this.individuals=[];this.businesses=[];this.mode="individuals";this.initialised=false;this.bound=false;this.onClick=this.onClick.bind(this);this.onSubmit=this.onSubmit.bind(this);this.onSearch=this.onSearch.bind(this);}
    async initialise(){if(this.initialised)return this;await auth.initialise();if(!auth.isAuthenticated()){window.location.replace("../auth/login.html?return="+encodeURIComponent(window.location.pathname));return this;}const role=await resolveUserDashboardRole(auth.getCurrentUser());if(role!=="SUPER_ADMIN"){window.location.replace("./super-admin.html");return this;}this.bind();await this.load();this.initialised=true;return this;}
    accessToken(){return auth.getToken?.()||null;}
    async rest(path,options={}){const token=this.accessToken();const response=await fetch(`${authConfig.supabase.url}/rest/v1/${path}`,{...options,headers:{apikey:authConfig.supabase.publishableKey,Authorization:`Bearer ${token}`,"Content-Type":"application/json",Prefer:"return=representation",...(options.headers||{})}});const body=await response.json().catch(()=>[]);if(!response.ok)throw new Error(body?.message||body?.error||`Supabase request failed (${response.status}).`);return body;}
    async load(){this.setBusy(true);try{const [profiles,businesses]=await Promise.all([this.rest("profiles?role=eq.INDIVIDUAL&order=created_at.desc&select=id,email,first_name,last_name,phone,is_active,avatar_url,created_at,updated_at"),this.rest("businesses?order=created_at.desc&select=id,owner_user_id,legal_name,trading_name,registration_number,tax_number,email,phone,is_active,logo_url,created_at,updated_at")]);this.individuals=Array.isArray(profiles)?profiles:[];this.businesses=Array.isArray(businesses)?businesses:[];this.render();}catch(error){console.error("[AdminAccountsController] Load failed",error);this.message(error.message||"Account data could not be loaded.","error");}finally{this.setBusy(false);}}
    bind(){if(this.bound)return;this.bound=true;document.addEventListener("click",this.onClick);document.addEventListener("submit",this.onSubmit);document.querySelector("#account-search")?.addEventListener("input",this.onSearch);document.querySelector("[data-auth-action='logout']")?.addEventListener("click",async e=>{e.preventDefault();await auth.logout({remote:true,reason:"user"});window.location.replace("../auth/login.html");});}
    onSearch(){this.renderTable();}
    onClick(event){const button=event.target.closest("[data-account-action]");if(!button)return;const action=button.dataset.accountAction;const id=button.dataset.id;const role=button.dataset.role;if(action==="individuals"||action==="businesses"){this.mode=action;document.querySelectorAll("[data-account-action='individuals'],[data-account-action='businesses']").forEach(el=>el.classList.toggle("active",el.dataset.accountAction===action));this.renderTable();return;}if(action==="new-individual")return this.openForm("create","INDIVIDUAL");if(action==="new-business")return this.openForm("create","BUSINESS");if(action==="edit")return this.openForm("edit",role,id);if(action==="toggle")return this.toggle(id,role,button.dataset.active==="true");if(action==="password")return this.openPassword(id,role);if(action==="close-modal")return this.closeModal();if(action==="refresh")return this.load();}
    async toggle(id,role,active){const verb=active?"deactivate":"activate";if(!confirm(`Are you sure you want to ${verb} this ${role.toLowerCase()} account?`))return;try{await adminAccountsData.setActive(id,!active,role);await this.load();this.message(`Account ${verb}d successfully.`,"success");}catch(error){this.message(error.message,"error");}}
    openForm(action,role,id=""){
        const record=role==="INDIVIDUAL"?this.individuals.find(x=>x.id===id):this.businesses.find(x=>x.owner_user_id===id);
        const business=role==="BUSINESS";const edit=action==="edit";const assetUrl=business?record?.logo_url:record?.avatar_url;const host=document.querySelector("#account-modal");if(!host)return;
        host.innerHTML=`<div class="modal-backdrop" data-account-action="close-modal"></div><section class="modal-card" role="dialog" aria-modal="true"><div class="modal-header"><div><p class="eyebrow">Super Admin</p><h2>${edit?"Edit":"Create"} ${business?"Business":"Individual"}</h2><p>${business?"Optional business logo for account and invoice presentation.":"Optional clear profile photograph for account and invoice presentation."}</p></div><button type="button" class="icon-button" data-account-action="close-modal">×</button></div><form id="account-form" data-action="${action}" data-role="${role}" data-id="${esc(id)}" enctype="multipart/form-data"><div class="form-grid"><label>Email<input name="email" type="email" required value="${esc(record?.email||"")}></label><label>Phone<input name="phone" type="tel" value="${esc(record?.phone||"")}></label><label>First name<input name="first_name" ${business?"":"required"} value="${esc(record?.first_name||"")}></label><label>Last name<input name="last_name" value="${esc(record?.last_name||"")}></label>${business?`<label>Legal name<input name="legal_name" required value="${esc(record?.legal_name||"")}></label><label>Trading name<input name="trading_name" value="${esc(record?.trading_name||"")}></label><label>Registration number<input name="registration_number" value="${esc(record?.registration_number||"")}></label><label>Tax number<input name="tax_number" value="${esc(record?.tax_number||"")}></label>`:""}${!edit?`<label>Temporary password<input name="password" type="password" minlength="8" required autocomplete="new-password"></label>`:""}</div><div class="asset-upload-panel"><div class="asset-upload-copy"><strong>${business?"Business logo":"Individual profile photo"}</strong><span>Optional · JPEG, PNG or WebP · maximum 5 MB</span>${assetUrl?`<a href="${esc(assetUrl)}" target="_blank" rel="noopener">Current image</a>`:"<span>No image uploaded</span>"}</div><label class="btn btn-secondary asset-upload-button">${business?"Upload Logo":"Upload Photo"}<input id="account-brand-asset" name="brand_asset" type="file" accept="image/jpeg,image/png,image/webp" hidden></label><div id="asset-preview" class="asset-preview">${assetUrl?`<img src="${esc(assetUrl)}" alt="Current ${business?"business logo":"profile photo"}">`:""}</div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-account-action="close-modal">Cancel</button><button class="btn btn-primary" type="submit">${edit?"Save Changes":"Create Account"}</button></div></form></section>`;
        host.hidden=false;const fileInput=host.querySelector("#account-brand-asset");fileInput?.addEventListener("change",()=>{const file=fileInput.files?.[0];const preview=host.querySelector("#asset-preview");if(!file||!preview)return;const url=URL.createObjectURL(file);preview.innerHTML=`<img src="${esc(url)}" alt="Selected ${business?"business logo":"profile photo"}">`;});host.querySelector("input")?.focus();
    }
    openPassword(id,role){const host=document.querySelector("#account-modal");if(!host)return;host.innerHTML=`<div class="modal-backdrop" data-account-action="close-modal"></div><section class="modal-card" role="dialog" aria-modal="true"><div class="modal-header"><div><p class="eyebrow">Security</p><h2>Reset Password</h2></div><button type="button" class="icon-button" data-account-action="close-modal">×</button></div><form id="password-form" data-role="${role}" data-id="${esc(id)}"><label>New temporary password<input name="password" type="password" minlength="8" required autocomplete="new-password"></label><div class="modal-footer"><button type="button" class="btn btn-secondary" data-account-action="close-modal">Cancel</button><button class="btn btn-primary">Reset Password</button></div></form></section>`;host.hidden=false;host.querySelector("input")?.focus();}
    async onSubmit(event){
        if(!["account-form","password-form"].includes(event.target.id))return;event.preventDefault();const form=event.target;const data=Object.fromEntries(new FormData(form).entries());const action=form.dataset.action,role=form.dataset.role,id=form.dataset.id;try{this.setBusy(true);if(form.id==="password-form"){await adminAccountsData.resetPassword(id,data.password,role);}else{let result;if(action==="create")result=role==="INDIVIDUAL"?await adminAccountsData.createIndividual(data):await adminAccountsData.createBusiness(data);else result=role==="INDIVIDUAL"?await adminAccountsData.updateIndividual(id,data):await adminAccountsData.updateBusiness(id,data);const targetId=result?.user_id||id;if(data.brand_asset instanceof File&&data.brand_asset.size>0){await adminBrandAssetService.upload({role,userId:targetId,file:data.brand_asset});}}this.closeModal();await this.load();this.message("Account saved successfully.","success");}catch(error){this.message(error.message||"The account operation failed.","error");}finally{this.setBusy(false);}}
    render(){const all=[...this.individuals,...this.businesses];document.querySelector("#account-individual-count").textContent=this.individuals.length;document.querySelector("#account-business-count").textContent=this.businesses.length;document.querySelector("#account-active-count").textContent=all.filter(x=>x.is_active).length;this.renderTable();}
    renderTable(){const tbody=document.querySelector("#accounts-table");if(!tbody)return;const search=String(document.querySelector("#account-search")?.value||"").toLowerCase();const records=this.mode==="individuals"?this.individuals.map(x=>({...x,accountRole:"INDIVIDUAL",displayName:`${x.first_name||""} ${x.last_name||""}`.trim()})):this.businesses.map(x=>({...x,accountRole:"BUSINESS",displayName:x.trading_name||x.legal_name}));const filtered=records.filter(x=>`${x.displayName} ${x.email||""} ${x.phone||""} ${x.registration_number||""}`.toLowerCase().includes(search));tbody.innerHTML=filtered.length?filtered.map(x=>`<tr><td><div class="account-cell">${x.accountRole==="BUSINESS"?(x.logo_url?`<img class="account-avatar" src="${esc(x.logo_url)}" alt="">`:`<span class="account-avatar account-avatar-empty">B</span>`):(x.avatar_url?`<img class="account-avatar" src="${esc(x.avatar_url)}" alt="">`:`<span class="account-avatar account-avatar-empty">I</span>`)}<div><strong>${esc(x.displayName||"Unnamed")}</strong><small>${esc(x.email||"")}</small></div></div></td><td>${esc(x.phone||"—")}</td><td>${x.accountRole==="BUSINESS"?esc(x.registration_number||"—"):"Individual"}</td><td><span class="status-badge ${x.is_active?"active":"inactive"}">${x.is_active?"Active":"Inactive"}</span></td><td>${this.formatDate(x.updated_at||x.created_at)}</td><td class="row-actions"><button class="btn btn-small" data-account-action="edit" data-role="${x.accountRole}" data-id="${esc(x.accountRole==="BUSINESS"?x.owner_user_id:x.id)}">Edit</button><button class="btn btn-small btn-secondary" data-account-action="password" data-role="${x.accountRole}" data-id="${esc(x.accountRole==="BUSINESS"?x.owner_user_id:x.id)}">Password</button><button class="btn btn-small ${x.is_active?"btn-danger":"btn-primary"}" data-account-action="toggle" data-role="${x.accountRole}" data-id="${esc(x.accountRole==="BUSINESS"?x.owner_user_id:x.id)}" data-active="${x.is_active}">${x.is_active?"Deactivate":"Activate"}</button></td></tr>`).join(""):`<tr><td colspan="6" class="empty-state">No ${this.mode==="individuals"?"individual":"business"} accounts found.</td></tr>`;}
    formatDate(v){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("en-ZA",{dateStyle:"medium",timeStyle:"short"}).format(d);}
    closeModal(){const modal=document.querySelector("#account-modal");if(modal){modal.hidden=true;modal.innerHTML="";}}
    setBusy(v){document.body.classList.toggle("is-busy",Boolean(v));}
    message(text,type){const el=document.querySelector("#account-message");if(!el)return;el.hidden=false;el.className=`login-message ${type==="error"?"login-error":"login-success"}`;el.textContent=text;setTimeout(()=>el.hidden=true,5000);}
}
export const adminAccountsController=new AdminAccountsController();export default adminAccountsController;
