import auth from "../auth/AuthService.js";
import authConfig from "../auth/auth.config.js";
import navigation from "../core/navigation.js";
import { resolveUserDashboardRole } from "./DashboardAccess.js";

class AnalyticsController {
    constructor(){this.role=null;this.initialised=false;this.data={matters:[],invoices:[],staff:[],assignments:[],profiles:[],businesses:[]};this.onPeriod=this.onPeriod.bind(this);}
    async initialise(){if(this.initialised)return this;await auth.initialise();if(!auth.isAuthenticated()){navigation.toLogin(window.location.pathname,{replace:true});return this;}this.role=await resolveUserDashboardRole(auth.getCurrentUser());if(!["SUPER_ADMIN","STAFF"].includes(this.role)){navigation.toRoleDashboard(this.role,{replace:true});return this;}if(this.role==="STAFF"&&!(await this.permission("view_analytics"))){this.showMessage("You do not have permission to view analytics.");return this;}document.querySelector("#analytics-period")?.addEventListener("change",this.onPeriod);document.querySelector("[data-auth-action='logout']")?.addEventListener("click",async e=>{e.preventDefault();await auth.logout({remote:true,reason:"user"});navigation.toLogin(null,{replace:true});});await this.load();this.initialised=true;return this;}
    token(){const t=auth.getToken();if(!t)throw new Error("Your session has expired. Please sign in again.");return t;}
    async request(path){const r=await fetch(`${authConfig.supabase.url}/rest/v1/${path}`,{headers:{Accept:"application/json",apikey:authConfig.supabase.publishableKey,Authorization:`Bearer ${this.token()}`}});const raw=await r.text();let d=[];try{d=raw?JSON.parse(raw):[];}catch{}if(!r.ok)throw new Error(d?.message||d?.hint||`Analytics request failed (${r.status}).`);return Array.isArray(d)?d:[];}
    async rpc(name,payload){const r=await fetch(`${authConfig.supabase.url}/rest/v1/rpc/${name}`,{method:"POST",headers:{Accept:"application/json",apikey:authConfig.supabase.publishableKey,Authorization:`Bearer ${this.token()}`,"Content-Type":"application/json"},body:JSON.stringify(payload)});const raw=await r.text();let d=null;try{d=raw?JSON.parse(raw):null;}catch{}if(!r.ok)throw new Error(d?.message||`Permission request failed (${r.status}).`);return d;}
    async permission(key){if(this.role==="SUPER_ADMIN")return true;try{return Boolean(await this.rpc("has_staff_permission",{p_permission_key:key}));}catch{return false;}}
    async load(){this.setBusy(true);try{const [matters,invoices,staff,assignments,profiles,businesses]=await Promise.all([this.request("matters?select=id,title,status,priority,created_at,updated_at&order=created_at.asc&limit=2000"),this.request("invoices?select=id,amount,amount_paid,status,created_at&order=created_at.asc&limit=2000"),this.request("staff?select=id,employee_number,department,is_active,created_at&order=created_at.asc&limit=500"),this.request("assignments?select=id,matter_id,staff_id,status,assigned_at,completed_at&order=assigned_at.asc&limit=2000"),this.request("profiles?role=eq.INDIVIDUAL&select=id,created_at,is_active&limit=2000"),this.request("businesses?select=id,created_at,is_active&limit=2000")]);this.data={matters,invoices,staff,assignments,profiles,businesses};this.render();}catch(e){console.error("[AnalyticsController] load failed",e);this.showMessage(e.message);}finally{this.setBusy(false);}}
    onPeriod(){this.render();}
    range(){const days=Number(document.querySelector("#analytics-period")?.value||30),to=new Date(),from=new Date(to);from.setDate(from.getDate()-days);return{from,to};}
    within(item){const {from,to}=this.range();const d=new Date(item.created_at||item.updated_at||item.assigned_at);return d>=from&&d<=to;}
    render(){const m=this.data.matters.filter(x=>this.within(x)),i=this.data.invoices.filter(x=>this.within(x)),clients=this.data.profiles.filter(x=>this.within(x)).length+this.data.businesses.filter(x=>this.within(x)).length,completed=m.filter(x=>["COMPLETED","CLOSED"].includes(String(x.status).toUpperCase())).length,revenue=i.reduce((s,x)=>s+Number(x.amount_paid||0),0);this.set("#new-clients",clients);this.set("#new-matters",m.length);this.set("#completed-matters",completed);this.set("#analytics-revenue",`R${revenue.toFixed(2)}`);this.set("#new-clients-change",`${this.data.profiles.length+this.data.businesses.length} total client records`);this.set("#new-matters-change",`${m.filter(x=>String(x.priority).toUpperCase()==="URGENT").length} urgent`);this.set("#completed-matters-change",m.length?`${Math.round(completed/m.length*100)}% of period matters`:"No period matters");this.set("#analytics-revenue-change",`${i.length} invoice record(s)`);this.renderChart(m);this.renderServices(m);this.renderDepartments(m);this.renderStaff();}
    renderChart(matters){const canvas=document.querySelector("#matter-activity-canvas");if(!canvas)return;const ctx=canvas.getContext("2d"),box=canvas.parentElement;const width=Math.max(320,box.clientWidth||700),height=280,dpr=window.devicePixelRatio||1;canvas.width=width*dpr;canvas.height=height*dpr;canvas.style.width=`${width}px`;canvas.style.height=`${height}px`;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);const buckets=Number(document.querySelector("#analytics-period")?.value||30)<=30?14:12,labels=[],opened=Array(buckets).fill(0),done=Array(buckets).fill(0),from=this.range().from;for(let n=0;n<buckets;n++){labels.push(String(n+1));}for(const m of matters){const d=new Date(m.created_at);const index=Math.min(buckets-1,Math.max(0,Math.floor((d-from)/(this.range().to-from)*buckets)));opened[index]++;if(["COMPLETED","CLOSED"].includes(String(m.status).toUpperCase()))done[index]++;}const max=Math.max(1,...opened,...done),left=42,right=12,top=18,bottom=36,plotW=width-left-right,plotH=height-top-bottom;ctx.strokeStyle="#b8b8b8";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(left,top);ctx.lineTo(left,top+plotH);ctx.lineTo(width-right,top+plotH);ctx.stroke();const draw=(values,offset)=>{ctx.beginPath();values.forEach((v,n)=>{const x=left+(n/(buckets-1||1))*plotW,y=top+plotH-(v/max)*plotH;if(n===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.stroke();};draw(opened,0);draw(done,0);ctx.fillStyle="#666";ctx.font="12px Arial";ctx.fillText("Opened",left,12);ctx.fillText("Completed",left+70,12);}
    renderServices(matters){const el=document.querySelector("#service-breakdown");if(!el)return;const map={};for(const m of matters){const key=String(m.title||"Uncategorised").split(/[-:]/)[0].trim()||"Uncategorised";map[key]=(map[key]||0)+1;}const rows=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,8);el.innerHTML=rows.length?rows.map(([k,v])=>`<div class="activity-row"><span>${this.escape(k)}</span><strong>${v}</strong></div>`).join(""):"<div class='empty-state'>No matter activity in the selected period.</div>";}
    renderDepartments(matters){const el=document.querySelector("#department-performance");if(!el)return;const map={};for(const a of this.data.assignments){const staff=this.data.staff.find(x=>x.id===a.staff_id);const key=staff?.department||"Unassigned";map[key]??={matters:new Set(),completed:0,revenue:0};if(a.matter_id)map[key].matters.add(a.matter_id);if(String(a.status).toUpperCase()==="COMPLETED")map[key].completed++;}const rows=Object.entries(map);el.innerHTML=rows.length?rows.map(([k,v])=>`<tr><td>${this.escape(k)}</td><td>${v.matters.size}</td><td>${v.completed}</td><td>${Math.max(0,v.matters.size-v.completed)}</td><td>—</td></tr>`).join(""):"<tr><td colspan='5'>No assignment data is available.</td></tr>";}
    renderStaff(){const el=document.querySelector("#staff-performance");if(!el)return;const rows=this.data.staff.map(s=>{const a=this.data.assignments.filter(x=>x.staff_id===s.id),c=a.filter(x=>String(x.status).toUpperCase()==="COMPLETED").length;return `<div class="activity-row"><span>${this.escape(s.employee_number||s.id)} · ${this.escape(s.department||"—")}</span><strong>${c}/${a.length}</strong></div>`;});el.innerHTML=rows.length?rows.join(""):"<div class='empty-state'>No staff records available.</div>";}
    set(selector,value){const e=document.querySelector(selector);if(e)e.textContent=String(value);}
    escape(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
    showMessage(message){let e=document.querySelector("#analytics-message");if(!e){e=document.createElement("div");e.id="analytics-message";e.className="login-message login-error";document.querySelector(".dashboard-page")?.prepend(e);}e.hidden=false;e.textContent=message;}
    setBusy(v){document.body.classList.toggle("is-busy",Boolean(v));}
}
export const analyticsController=new AnalyticsController();
export default analyticsController;
