import auth from "../auth/AuthService.js";
import navigation from "../core/navigation.js";
import assignmentData from "./AssignmentDataService.js";
import { resolveUserDashboardRole } from "./DashboardAccess.js";

const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");

class AssignmentController{
 constructor(){this.role=null;this.rows=[];this.staff=[];this.matters=[];this.canManage=false;this.bound=false;this.onClick=this.onClick.bind(this);this.onSubmit=this.onSubmit.bind(this);}
 async initialise(){await auth.initialise();if(!auth.isAuthenticated()){navigation.toLogin(location.pathname,{replace:true});return;}this.role=await resolveUserDashboardRole(auth.getCurrentUser());if(!["SUPER_ADMIN","STAFF"].includes(this.role)){navigation.toRoleDashboard(this.role,{replace:true});return;}this.canManage=this.role==="SUPER_ADMIN"||await this.permission("manage_assignments");this.bind();await this.load();}
 async permission(key){try{const token=auth.getToken();const r=await fetch(`${auth.config?.supabase?.url||""}/rest/v1/rpc/has_staff_permission`,{method:"POST",headers:{apikey:auth.getConfig?.()?.supabase?.publishableKey||"","Authorization":`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({p_permission_key:key})});return r.ok&&Boolean(await r.json());}catch{return false;}}
 bind(){if(this.bound)return;this.bound=true;document.addEventListener("click",this.onClick);document.addEventListener("submit",this.onSubmit);document.querySelector("[data-auth-action='logout']")?.addEventListener("click",async e=>{e.preventDefault();await auth.logout({remote:true,reason:"user"});navigation.toLogin(null,{replace:true});});}
 async load(){try{this.rows=await assignmentData.list();this.rows=Array.isArray(this.rows)?this.rows:[];this.render();}catch(e){this.message(e.message,"error");}}
 async openCreate(){if(!this.canManage)return this.message("You do not have permission to manage assignments.","error");try{const t=await assignmentData.targets();this.staff=t.staff.filter(s=>s.is_active);this.matters=t.matters;const assigned=new Set(this.rows.filter(x=>x.status==="ACTIVE"&&x.matter_id).map(x=>x.matter_id));this.matters=this.matters.filter(m=>!assigned.has(m.id));this.openModal(`<div class="modal-backdrop" data-assignment-action="close"></div><section class="modal-card"><div class="modal-header"><div><p class="eyebrow">Live Supabase</p><h2>Assign Matter</h2></div><button class="icon-button" data-assignment-action="close">×</button></div><form id="assignment-form"><div class="form-grid"><label>Matter<select name="matter_id" required><option value="">Select matter</option>${this.matters.map(m=>`<option value="${m.id}">${esc(m.reference_number||"No reference")} — ${esc(m.title)}</option>`).join("")}</select></label><label>Staff<select name="staff_id" required><option value="">Select active staff</option>${this.staff.map(s=>`<option value="${s.id}">${esc(s.employee_number||s.user_id)} — ${esc(s.department||"Unassigned")}</option>`).join("")}</select></label><label class="form-wide">Notes<textarea name="notes" rows="4" maxlength="2000"></textarea></label></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-assignment-action="close">Cancel</button><button class="btn btn-primary">Assign Matter</button></div></form></section>`);}catch(e){this.message(e.message,"error");}}
 onClick(e){const b=e.target.closest("[data-assignment-action]");if(!b)return;const a=b.dataset.assignmentAction;if(a==="new")return this.openCreate();if(a==="refresh")return this.load();if(a==="close")return this.close();if(a==="complete")return this.setStatus(b.dataset.id,"COMPLETED");if(a==="cancel")return this.setStatus(b.dataset.id,"CANCELLED");}
 async setStatus(id,status){if(!this.canManage)return this.message("You do not have permission to manage assignments.","error");try{await assignmentData.update(id,{status,completed_at:status==="COMPLETED"?new Date().toISOString():null});await this.load();}catch(e){this.message(e.message,"error");}}
 async onSubmit(e){if(e.target.id!=="assignment-form")return;e.preventDefault();if(!this.canManage)return this.message("You do not have permission to manage assignments.","error");const raw=Object.fromEntries(new FormData(e.target).entries());try{await assignmentData.create({matter_id:raw.matter_id,staff_id:raw.staff_id,assigned_by:auth.getCurrentUser().id,status:"ACTIVE",notes:String(raw.notes||"").trim()||null});this.close();await this.load();this.message("Matter assigned successfully.","success");}catch(err){this.message(err.message,"error");}}
 render(){const rows=this.rows;this.set("#assignment-active",rows.filter(x=>x.status==="ACTIVE").length);this.set("#assignment-completed",rows.filter(x=>x.status==="COMPLETED").length);this.set("#assignment-staff",new Set(rows.filter(x=>x.status==="ACTIVE").map(x=>x.staff_id)).size);const tbody=document.querySelector("#assignments-table");if(!tbody)return;tbody.innerHTML=rows.length?rows.map(x=>`<tr><td><strong>${esc(x.matter?.reference_number||"—")}</strong><br>${esc(x.matter?.title||"Matter")}</td><td>${esc(x.staff?.employee_number||x.staff_id)}</td><td>${esc(x.staff?.department||"—")}</td><td>${esc(x.status)}</td><td>${this.date(x.assigned_at)}</td><td>${this.canManage&&x.status==="ACTIVE"?`<button class="btn btn-small" data-assignment-action="complete" data-id="${x.id}">Complete</button><button class="btn btn-small btn-secondary" data-assignment-action="cancel" data-id="${x.id}">Cancel</button>`:"—"}</td></tr>`).join(""):"<tr><td colspan=\"6\" class=\"empty-state\">No assignments found.</td></tr>";document.querySelector("[data-assignment-action='new']")?.toggleAttribute("disabled",!this.canManage);}
 openModal(html){const x=document.querySelector("#assignment-modal");if(x){x.innerHTML=html;x.hidden=false;x.querySelector("select,input,textarea")?.focus();}}
 close(){const x=document.querySelector("#assignment-modal");if(x){x.hidden=true;x.innerHTML="";}}
 message(text,type){const x=document.querySelector("#assignment-message");if(x){x.hidden=false;x.className=`login-message ${type==="error"?"login-error":"login-success"}`;x.textContent=text;}}
 set(s,v){const x=document.querySelector(s);if(x)x.textContent=String(v);}
 date(v){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("en-ZA",{dateStyle:"medium",timeStyle:"short"}).format(d);}
}
export default new AssignmentController();
