import auth from "../auth/AuthService.js";
import authConfig from "../auth/auth.config.js";
import navigation from "../core/navigation.js";
import { resolveUserDashboardRole } from "./DashboardAccess.js";

const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");
class CaseController{
 constructor(){this.role=null;this.rows=[];this.matters=[];this.permissions={};this.bound=false;this.onClick=this.onClick.bind(this);this.onSubmit=this.onSubmit.bind(this);}
 async initialise(){await auth.initialise();if(!auth.isAuthenticated())return navigation.toLogin(location.pathname,{replace:true});this.role=await resolveUserDashboardRole(auth.getCurrentUser());if(!["SUPER_ADMIN","STAFF"].includes(this.role))return navigation.toRoleDashboard(this.role,{replace:true});this.permissions=this.role==="SUPER_ADMIN"?{view_cases:true,create_cases:true,edit_cases:true}:{view_cases:await this.permission("view_cases"),create_cases:await this.permission("create_cases"),edit_cases:await this.permission("edit_cases")};if(!this.permissions.view_cases)return this.message("You do not have permission to view cases.","error");this.bind();await this.load();}
 async request(path,options={}){const token=auth.getToken();const r=await fetch(`${authConfig.supabase.url}/rest/v1/${path}`,{...options,headers:{Accept:"application/json",apikey:authConfig.supabase.publishableKey,Authorization:`Bearer ${token}`,"Content-Type":"application/json",Prefer:"return=representation",...(options.headers||{})}});const b=await r.json().catch(()=>[]);if(!r.ok)throw new Error(b?.message||b?.details||b?.hint||`Case request failed (${r.status}).`);return b;}
 async permission(key){try{const token=auth.getToken();const r=await fetch(`${authConfig.supabase.url}/rest/v1/rpc/has_staff_permission`,{method:"POST",headers:{apikey:authConfig.supabase.publishableKey,Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({p_permission_key:key})});return r.ok&&Boolean(await r.json());}catch{return false;}}
 bind(){if(this.bound)return;this.bound=true;document.addEventListener("click",this.onClick);document.addEventListener("submit",this.onSubmit);document.querySelector("[data-auth-action='logout']")?.addEventListener("click",async e=>{e.preventDefault();await auth.logout({remote:true,reason:"user"});navigation.toLogin(null,{replace:true});});}
 async load(){try{this.rows=await this.request("cases?select=id,matter_id,case_number,title,description,status,created_by,created_at,updated_at,matter:matter_id(id,reference_number,title)&order=created_at.desc");this.rows=Array.isArray(this.rows)?this.rows:[];this.render();}catch(e){this.message(e.message,"error");}}
 async openForm(mode,row={}){if(mode==="create"&&!this.permissions.create_cases)return this.message("You do not have permission to create cases.","error");if(mode==="edit"&&!this.permissions.edit_cases)return this.message("You do not have permission to edit cases.","error");try{if(!this.matters.length)this.matters=await this.request("matters?select=id,reference_number,title&order=created_at.desc");this.openModal(`<div class="modal-backdrop" data-case-action="close"></div><section class="modal-card"><div class="modal-header"><div><p class="eyebrow">Live Supabase</p><h2>${mode==="create"?"Create":"Edit"} Case</h2></div><button class="icon-button" data-case-action="close">×</button></div><form id="case-form" data-mode="${mode}" data-id="${esc(row.id||"")}"><div class="form-grid"><label>Matter<select name="matter_id" required><option value="">Select matter</option>${this.matters.map(m=>`<option value="${m.id}" ${m.id===row.matter_id?"selected":""}>${esc(m.reference_number||"—")} — ${esc(m.title)}</option>`).join("")}</select></label><label>Case number<input name="case_number" value="${esc(row.case_number||"")}" maxlength="100"></label><label>Title<input name="title" required maxlength="200" value="${esc(row.title||"")}"></label><label>Status<select name="status"><option value="OPEN" ${row.status==="OPEN"?"selected":""}>Open</option><option value="CLOSED" ${row.status==="CLOSED"?"selected":""}>Closed</option><option value="PENDING" ${row.status==="PENDING"?"selected":""}>Pending</option></select></label><label class="form-wide">Description<textarea name="description" rows="5">${esc(row.description||"")}</textarea></label></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-case-action="close">Cancel</button><button class="btn btn-primary">${mode==="create"?"Create Case":"Save Changes"}</button></div></form></section>`);}catch(e){this.message(e.message,"error");}}
 onClick(e){const b=e.target.closest("[data-case-action]");if(!b)return;const a=b.dataset.caseAction;if(a==="new")return this.openForm("create");if(a==="edit")return this.openForm("edit",this.rows.find(x=>x.id===b.dataset.id)||{});if(a==="refresh")return this.load();if(a==="close")return this.close();}
 async onSubmit(e){if(e.target.id!=="case-form")return;e.preventDefault();const f=e.target,raw=Object.fromEntries(new FormData(f).entries()),p={matter_id:raw.matter_id,title:String(raw.title||"").trim(),case_number:String(raw.case_number||"").trim()||null,description:String(raw.description||"").trim()||null,status:raw.status||"OPEN"};try{if(f.dataset.mode==="create"){p.created_by=auth.getCurrentUser().id;await this.request("cases",{method:"POST",body:JSON.stringify(p)});}else await this.request(`cases?id=eq.${encodeURIComponent(f.dataset.id)}`,{method:"PATCH",body:JSON.stringify(p)});this.close();await this.load();this.message("Case saved successfully.","success");}catch(err){this.message(err.message,"error");}}
 render(){const t=document.querySelector("#cases-table");if(!t)return;t.innerHTML=this.rows.length?this.rows.map(x=>`<tr><td>${esc(x.case_number||"—")}</td><td>${esc(x.matter?.reference_number||"—")}</td><td>${esc(x.title)}</td><td>${esc(x.status)}</td><td>${this.date(x.created_at)}</td><td>${this.permissions.edit_cases?`<button class="btn btn-small" data-case-action="edit" data-id="${x.id}">Open / Edit</button>`:"—"}</td></tr>`).join(""):"<tr><td colspan=\"6\" class=\"empty-state\">No cases found.</td></tr>";document.querySelector("[data-case-action='new']")?.toggleAttribute("disabled",!this.permissions.create_cases);}
 openModal(h){const x=document.querySelector("#case-modal");if(x){x.innerHTML=h;x.hidden=false;x.querySelector("select,input,textarea")?.focus();}}
 close(){const x=document.querySelector("#case-modal");if(x){x.hidden=true;x.innerHTML="";}}
 message(m,type){const x=document.querySelector("#case-message");if(x){x.hidden=false;x.className=`login-message ${type==="error"?"login-error":"login-success"}`;x.textContent=m;}}
 date(v){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("en-ZA",{dateStyle:"medium",timeStyle:"short"}).format(d);}
}
export default new CaseController();
