import auth from "../auth/AuthService.js";
import authConfig from "../auth/auth.config.js";
import adminBrandAssetService from "./AdminBrandAssetService.js";

const REST=`${authConfig.supabase.url}/rest/v1`;const STORAGE=`${authConfig.supabase.url}/storage/v1/object/organisation-documents`;const INGEST=`${authConfig.supabase.url}/functions/v1/admin-organisation-document-ingest`;
const DEFAULTS={legal_name:"Isaacs & Partners",trading_name:"",entity_type:"Private Company",country:"South Africa",default_currency:"ZAR",default_vat_rate:15,quote_prefix:"QUO-",invoice_prefix:"INV-",receipt_prefix:"REC-",credit_note_prefix:"CN-",debit_note_prefix:"DN-",quote_validity_days:7,vat_registered:false,paye_registered:false,uif_registered:false,sdl_registered:false,is_active:true};
const CATEGORIES={BUSINESS_OPERATION_MANUAL:["Business Operation Manual","STAFF"],CONFIDENTIALITY_NDA_NON_SOLICITATION:["Confidentiality / NDA / Non-Solicitation","ALL"],DEPOSIT_RETAINER_REPATRIATION_LIABILITY:["Deposit, Retainer & Repatriation Liability","CLIENT_ALL"],EMPLOYER_UNDERTAKINGS:["Employer Undertakings","BUSINESS"],INTERNAL_REVENUE_ALLOCATION:["Internal Revenue Allocation","STAFF"],MANDATE_AND_FEE:["Mandate & Fee Agreement","CLIENT_ALL"],MATTER_OPENING_CLIENT_ALLOCATION:["Matter Opening & Client Allocation Agreements","ALL"],TERMS_OF_SERVICE:["Terms of Service","CLIENT_ALL"],OTHER:["Other Core Business Document","ALL"]};
const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
class OrganisationProfileService{
 constructor(){this.profile=null;this.documents=[];this.bound=false;}
 token(){const t=auth.getToken();if(!t)throw new Error("Your session has expired. Please sign in again.");return t;}
 async request(path,options={}){const r=await fetch(`${REST}/${path}`,{...options,headers:{Accept:"application/json",apikey:authConfig.supabase.publishableKey,Authorization:`Bearer ${this.token()}`,"Content-Type":"application/json",Prefer:"return=representation",...(options.headers||{})}});const raw=await r.text();let b=null;try{b=raw?JSON.parse(raw):null;}catch{b=raw;}if(!r.ok)throw new Error(b?.message||b?.hint||b?.details||String(b||`Request failed (${r.status}).`));return b;}
 async initialise(){await auth.initialise();if(!auth.isAuthenticated())return this;this.bind();await this.load();return this;}
 bind(){if(this.bound)return;this.bound=true;document.querySelector("#organisation-profile-form")?.addEventListener("submit",e=>{e.preventDefault();void this.saveProfile();});document.querySelector("#organisation-document-form")?.addEventListener("submit",e=>{e.preventDefault();void this.uploadDocument();});document.querySelector("#organisation-refresh")?.addEventListener("click",()=>void this.load());document.querySelector("#organisation-document-list")?.addEventListener("click",e=>{const b=e.target.closest("[data-document-action]");if(b?.dataset.documentAction==="route")void this.routeDocument(b.dataset.id);});}
 async load(){try{const[p,d]=await Promise.all([this.request("organisation_profiles?select=*&is_active=eq.true&limit=1"),this.request("organisation_documents?select=*&order=created_at.desc")]);this.profile=Array.isArray(p)&&p[0]?p[0]:{...DEFAULTS};this.documents=Array.isArray(d)?d:[];this.renderProfile();this.renderDocuments();this.renderStatus();}catch(e){this.message(e.message,true);}}
 renderProfile(){const f=document.querySelector("#organisation-profile-form");if(!f)return;const p={...DEFAULTS,...(this.profile||{})};Object.entries(p).forEach(([k,v])=>{const el=f.elements[k];if(!el)return;if(el.type==="checkbox")el.checked=Boolean(v);else el.value=v??"";});const logo=document.querySelector("#organisation-logo-preview");if(logo){logo.src=p.logo_url||"";logo.hidden=!p.logo_url;}}
 async saveProfile(){const f=document.querySelector("#organisation-profile-form"),fd=new FormData(f),payload={};for(const[k,v]of fd.entries()){if(f.elements[k]?.type==="checkbox"||k==="logo_file")continue;payload[k]=String(v).trim()===""?null:v;}["vat_registered","paye_registered","uif_registered","sdl_registered","is_active"].forEach(k=>payload[k]=Boolean(f.elements[k]?.checked));payload.default_vat_rate=Number(f.elements.default_vat_rate?.value||0);payload.quote_validity_days=Number(f.elements.quote_validity_days?.value||7);try{this.setBusy(true,"Saving organisation master record…");const existing=this.profile?.id;if(existing)await this.request(`organisation_profiles?id=eq.${encodeURIComponent(existing)}`,{method:"PATCH",body:JSON.stringify({...payload,updated_at:new Date().toISOString()})});else{const created=await this.request("organisation_profiles",{method:"POST",body:JSON.stringify({...payload,created_by:auth.getCurrentUser().id})});this.profile=Array.isArray(created)?created[0]:created;}const logoFile=f.elements.logo_file?.files?.[0];if(logoFile){const result=await adminBrandAssetService.upload({role:"ORGANISATION",userId:this.profile?.id||existing,file:logoFile});if(result?.asset_url)await this.request(`organisation_profiles?id=eq.${encodeURIComponent(this.profile?.id||existing)}`,{method:"PATCH",body:JSON.stringify({logo_url:result.asset_url,updated_at:new Date().toISOString()})});}await this.load();this.message("Organisation master record saved. Quotes and invoices now capture the active issuer profile when created.");}catch(e){this.message(e.message,true);}finally{this.setBusy(false);}}
 async ingest(documentId){const r=await fetch(INGEST,{method:"POST",headers:{Authorization:`Bearer ${this.token()}`,apikey:authConfig.supabase.publishableKey,"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({document_id:documentId})});const raw=await r.text();let b={};try{b=raw?JSON.parse(raw):{};}catch{}if(!r.ok)throw new Error(b?.error||`Document ingestion failed (${r.status}).`);return b;}
 async uploadDocument(){const f=document.querySelector("#organisation-document-form"),file=f.elements.file.files?.[0];if(!file)return this.message("Select a policy, agreement, manual or terms document first.",true);if(!this.profile?.id)return this.message("Save the active organisation profile before uploading core business documents.",true);if(file.size>25*1024*1024)return this.message("Documents are limited to 25 MB.",true);const category=f.elements.category.value,[label,defaultAudience]=CATEGORIES[category]||CATEGORIES.OTHER,title=f.elements.title.value.trim()||label,audience=f.elements.audience.value||defaultAudience,documentId=crypto.randomUUID(),path=`${this.profile.id}/${documentId}/${file.name.replace(/[^A-Za-z0-9_.-]/g,"_")}`;try{this.setBusy(true,"Uploading document securely…");const sr=await fetch(`${STORAGE}/${encodeURIComponent(path)}`,{method:"POST",headers:{apikey:authConfig.supabase.publishableKey,Authorization:`Bearer ${this.token()}`,"x-upsert":"false","Content-Type":file.type||"application/octet-stream"},body:file});if(!sr.ok){const t=await sr.text();throw new Error(t||`Storage upload failed (${sr.status}).`);}let text=null,status="EXTRACTION_PENDING",error=null;if(/^(text\/|application\/json$|application\/xml$)/i.test(file.type)||/\.(txt|md|csv|json|xml|html?)$/i.test(file.name)){text=await file.text();status="EXTRACTED";}await this.request("organisation_documents",{method:"POST",body:JSON.stringify({id:documentId,organisation_profile_id:this.profile.id,title,category,audience,description:f.elements.description.value.trim()||null,file_name:file.name,mime_type:file.type||null,file_size:file.size,storage_path:path,extracted_text:text,extraction_status:status,extraction_error:error,is_terms_of_service:f.elements.is_terms_of_service.checked,version:f.elements.version.value.trim()||"1.0",effective_from:f.elements.effective_from.value||new Date().toISOString().slice(0,10),created_by:auth.getCurrentUser().id})});if(status==="EXTRACTION_PENDING"&&(/\.pdf$/i.test(file.name)||/\.docx?$/i.test(file.name))){this.message("Document uploaded. Reading PDF/DOCX text and routing applicable clauses…");await this.ingest(documentId);}else{await this.request("rpc/organisation_route_document",{method:"POST",body:JSON.stringify({p_document_id:documentId})});}f.reset();await this.load();this.message("Document uploaded, read and routed to the applicable audience. Only assigned recipients can see it.");}catch(e){this.message(e.message,true);}finally{this.setBusy(false);}}
 async routeDocument(id){try{const n=await this.request("rpc/organisation_route_document",{method:"POST",body:JSON.stringify({p_document_id:id})});this.message(`Document routing completed. ${Number(n||0)} new recipient assignments created.`);}catch(e){this.message(e.message,true);}}
 renderDocuments(){const h=document.querySelector("#organisation-document-list");if(!h)return;h.innerHTML=this.documents.length?this.documents.map(d=>`<article class="document-card"><div><strong>${esc(d.title)}</strong><span>${esc(CATEGORIES[d.category]?.[0]||d.category)} · ${esc(d.audience)} · v${esc(d.version)}</span><span>Extraction: ${esc(d.extraction_status)} · ${d.is_terms_of_service?"Terms of Service":"Core policy"}</span></div><button type="button" class="btn btn-small" data-document-action="route" data-id="${esc(d.id)}">Re-route</button></article>`).join(""):`<div class="empty-state">No organisation documents uploaded yet.</div>`;}
 renderStatus(){const p=this.profile,h=document.querySelector("#organisation-profile-status");if(!h)return;const ready=p&&p.legal_name&&p.registered_address&&p.email;h.innerHTML=`<strong>${ready?"Master record ready":"Master record incomplete"}</strong><span>${esc(p?.legal_name||"No active organisation profile")}</span><span>${this.documents.length} core documents indexed</span>`;}
 message(text,error=false){const e=document.querySelector("#organisation-message");if(!e)return;e.hidden=!text;e.textContent=text||"";e.className=`login-message ${error?"login-error":"login-success"}`;}
 setBusy(busy,text=""){document.querySelectorAll("#organisation-profile-form button,#organisation-document-form button").forEach(b=>b.disabled=busy);if(text)this.message(text);}
}
export{CATEGORIES};export default new OrganisationProfileService();
