import auth from "../auth/AuthService.js";
import authConfig from "../auth/auth.config.js";
import navigation from "../core/navigation.js";
import { resolveUserDashboardRole } from "./DashboardAccess.js";

const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;");
const money=v=>new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR"}).format(Number(v||0));
const today=()=>new Date().toISOString().slice(0,10);

class QuoteController{
 constructor(){this.role=null;this.rows=[];this.individuals=[];this.businesses=[];this.matters=[];this.permissions={};this.bound=false;this.onClick=this.onClick.bind(this);this.onSubmit=this.onSubmit.bind(this);}
 async initialise(){
  await auth.initialise();
  if(!auth.isAuthenticated())return navigation.toLogin(location.pathname,{replace:true});
  this.role=await resolveUserDashboardRole(auth.getCurrentUser());
  if(!["SUPER_ADMIN","STAFF"].includes(this.role))return navigation.toRoleDashboard(this.role,{replace:true});
  const keys=["view_quotes","create_quotes","edit_quotes","approve_quotes"];
  this.permissions=this.role==="SUPER_ADMIN"?Object.fromEntries(keys.map(k=>[k,true])):Object.fromEntries(await Promise.all(keys.map(async k=>[k,await this.permission(k)])));
  if(!this.permissions.view_quotes)return this.message("You do not have permission to view quotes.","error");
  this.bind();await this.load();
 }
 token(){const t=auth.getToken();if(!t)throw new Error("Your session has expired. Please sign in again.");return t;}
 async request(path,options={}){const r=await fetch(`${authConfig.supabase.url}/rest/v1/${path}`,{...options,headers:{Accept:"application/json",apikey:authConfig.supabase.publishableKey,Authorization:`Bearer ${this.token()}`,"Content-Type":"application/json",Prefer:"return=representation",...(options.headers||{})}});const raw=await r.text();let b=null;try{b=raw?JSON.parse(raw):null;}catch{b=raw;}if(!r.ok)throw new Error(b?.message||b?.hint||b?.details||String(b||`Quote request failed (${r.status}).`));return b;}
 async rpc(name,payload){const r=await fetch(`${authConfig.supabase.url}/rest/v1/rpc/${name}`,{method:"POST",headers:{Accept:"application/json",apikey:authConfig.supabase.publishableKey,Authorization:`Bearer ${this.token()}`,"Content-Type":"application/json"},body:JSON.stringify(payload)});const raw=await r.text();let b=null;try{b=raw?JSON.parse(raw):null;}catch{b=raw;}if(!r.ok)throw new Error(b?.message||b?.hint||b?.details||String(b||`Quote operation failed (${r.status}).`));return b;}
 async permission(k){try{return Boolean(await this.rpc("has_staff_permission",{p_permission_key:k}));}catch{return false;}}
 bind(){if(this.bound)return;this.bound=true;document.addEventListener("click",this.onClick);document.addEventListener("submit",this.onSubmit);document.querySelector("[data-auth-action='logout']")?.addEventListener("click",async e=>{e.preventDefault();await auth.logout({remote:true,reason:"user"});navigation.toLogin(null,{replace:true});});}
 async load(){try{const [quotes,individuals,businesses,matters]=await Promise.all([this.request("quotes?select=*&order=created_at.desc"),this.request("profiles?role=eq.INDIVIDUAL&is_active=eq.true&select=id,first_name,last_name,email&order=first_name"),this.request("businesses?is_active=eq.true&select=id,legal_name,trading_name,email&order=legal_name"),this.request("matters?select=id,reference_number,title,status,individual_user_id,business_id&order=updated_at.desc")]);this.rows=Array.isArray(quotes)?quotes:[];this.individuals=Array.isArray(individuals)?individuals:[];this.businesses=Array.isArray(businesses)?businesses:[];this.matters=Array.isArray(matters)?matters:[];this.render();}catch(e){console.error("[QuoteController] load failed",e);this.message(e.message,"error");}}
 clientName(row){if(row.individual_user_id){const x=this.individuals.find(v=>v.id===row.individual_user_id);return x?`${x.first_name||""} ${x.last_name||""}`.trim()||x.email:row.individual_user_id;}const x=this.businesses.find(v=>v.id===row.business_id);return x?(x.trading_name||x.legal_name):row.business_id||"Unlinked";}
 customerOptions(row={}){const i=this.individuals.map(x=>`<option value="individual:${x.id}" ${row.individual_user_id===x.id?"selected":""}>${esc(`${x.first_name||""} ${x.last_name||""}`.trim()||x.email)} — ${esc(x.email||"")}</option>`).join("");const b=this.businesses.map(x=>`<option value="business:${x.id}" ${row.business_id===x.id?"selected":""}>${esc(x.trading_name||x.legal_name)} — ${esc(x.email||"")}</option>`).join("");return `<optgroup label="Individuals">${i}</optgroup><optgroup label="Businesses">${b}</optgroup>`;}
 matterOptions(row={}){return this.matters.map(x=>`<option value="${x.id}" ${row.matter_id===x.id?"selected":""}>${esc(x.reference_number||x.title||x.id)} — ${esc(x.title||"")}</option>`).join("");}
 itemRows(){return `<tr data-item><td><input name="item_name" required></td><td><input name="item_description"></td><td><input name="quantity" type="number" min="0.001" step="0.001" value="1"></td><td><input name="rate" type="number" min="0" step="0.01" value="0"></td><td><input name="tax_rate" type="number" min="0" step="0.01" value="0"></td><td><button type="button" class="btn btn-small btn-danger" data-quote-action="remove-item">Remove</button></td></tr>`;}
 openForm(row={}){const edit=Boolean(row.id);if(edit&&!this.permissions.edit_quotes)return this.message("You do not have permission to edit quotes.","error");if(!edit&&!this.permissions.create_quotes)return this.message("You do not have permission to create quotes.","error");this.openModal(`<div class="modal-backdrop" data-quote-action="close"></div><section class="modal-card modal-wide"><div class="modal-header"><div><p class="eyebrow">${this.role} · Sales</p><h2>${edit?"Edit":"New"} Quote</h2><p>Customer, expiry, line items, discount, tax and terms.</p></div><button class="icon-button" type="button" data-quote-action="close">×</button></div><form id="quote-form" data-id="${esc(row.id||"")}"><div class="form-grid"><label>Customer<select name="customer" required><option value="">Select customer</option>${this.customerOptions(row)}</select></label><label>Matter<select name="matter_id"><option value="">No matter</option>${this.matterOptions(row)}</select></label><label>Quote reference<input name="reference_number" value="${esc(row.reference_number||"")}" placeholder="Auto-generated"></label><label>Quote date<input name="quote_date" type="date" value="${esc(row.quote_date||today())}"></label><label>Expiry date<input name="expiry_date" type="date" value="${esc(row.expiry_date||"")}"></label><label class="form-wide">Subject<input name="subject" required value="${esc(row.subject||row.description||"")}"></label><label class="form-wide">Description<textarea name="description" rows="3">${esc(row.description||"")}</textarea></label></div><div class="transaction-table-wrap"><table class="transaction-table"><thead><tr><th>Item</th><th>Description</th><th>Qty</th><th>Rate</th><th>Tax %</th><th></th></tr></thead><tbody id="quote-items">${this.itemRows()}</tbody></table><button type="button" class="btn btn-secondary" data-quote-action="add-item">+ Add line item</button></div><div class="form-grid"><label>Discount type<select name="discount_type"><option value="PERCENT">%</option><option value="FIXED">Amount</option></select></label><label>Discount value<input name="discount_value" type="number" min="0" step="0.01" value="0"></label><label>Tax %<input name="tax_rate" type="number" min="0" step="0.01" value="0"></label><label>Shipping<input name="shipping_charge" type="number" min="0" step="0.01" value="0"></label><label>Adjustment<input name="adjustment" type="number" step="0.01" value="0"></label><label class="form-wide">Customer notes<textarea name="customer_notes" rows="3">Looking forward to your business.</textarea></label><label class="form-wide">Terms & conditions<textarea name="terms" rows="4">Payment terms as agreed in the retainer and service agreement.</textarea></label></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-quote-action="close">Cancel</button><button class="btn btn-primary">${edit?"Save Quote":"Save as Draft"}</button></div></form></section>`);}
 onClick(e){const b=e.target.closest("[data-quote-action]");if(!b)return;const a=b.dataset.quoteAction;if(a==="new")return this.openForm();if(a==="edit")return this.openForm(this.rows.find(x=>x.id===b.dataset.id)||{});if(a==="refresh")return this.load();if(a==="close")return this.close();if(a==="add-item")return this.addItem();if(a==="remove-item")return b.closest("tr")?.remove();if(a==="approve")return this.approve(b.dataset.id);if(a==="send")return this.send(b.dataset.id);if(a==="accept")return this.decide(b.dataset.id,"ACCEPTED","APPROVED");if(a==="decline")return this.decide(b.dataset.id,"DECLINED","REJECTED");if(a==="convert")return this.convert(b.dataset.id);}
 addItem(){const body=document.querySelector("#quote-items");if(body){const t=document.createElement("tbody");t.innerHTML=this.itemRows();body.appendChild(t.firstElementChild);}}
 async onSubmit(e){if(e.target.id!=="quote-form")return;e.preventDefault();const f=e.target,fd=new FormData(f),customer=String(fd.get("customer")||"");const individual=customer.startsWith("individual:")?customer.slice(11):null;const business=customer.startsWith("business:")?customer.slice(9):null;const items=[...document.querySelectorAll("#quote-items [data-item]")].map(r=>({item_name:r.querySelector("[name='item_name']")?.value?.trim(),description:r.querySelector("[name='item_description']")?.value?.trim()||null,quantity:Number(r.querySelector("[name='quantity']")?.value||0),rate:Number(r.querySelector("[name='rate']")?.value||0),tax_rate:Number(r.querySelector("[name='tax_rate']")?.value||0)})).filter(x=>x.item_name&&x.quantity>0);if(!individual&&!business)return this.message("Select an individual or business customer.","error");if(!items.length)return this.message("Add at least one quoted item with a quantity.","error");try{if(f.dataset.id){if(!this.permissions.edit_quotes)throw new Error("You do not have permission to edit quotes.");await this.request(`quotes?id=eq.${encodeURIComponent(f.dataset.id)}`,{method:"PATCH",body:JSON.stringify({individual_user_id:individual,business_id:business,matter_id:fd.get("matter_id")||null,reference_number:fd.get("reference_number")||null,quote_date:fd.get("quote_date")||today(),expiry_date:fd.get("expiry_date")||null,subject:fd.get("subject"),description:fd.get("description")||fd.get("subject"),discount_type:fd.get("discount_type"),discount_value:Number(fd.get("discount_value")||0),tax_rate:Number(fd.get("tax_rate")||0),shipping_charge:Number(fd.get("shipping_charge")||0),adjustment:Number(fd.get("adjustment")||0),customer_notes:fd.get("customer_notes")||null,terms:fd.get("terms")||null,updated_by:auth.getCurrentUser().id})});}else{if(!this.permissions.create_quotes)throw new Error("You do not have permission to create quotes.");await this.rpc("create_quote_transaction",{p_matter_id:fd.get("matter_id")||null,p_individual_user_id:individual,p_business_id:business,p_reference_number:fd.get("reference_number")||null,p_quote_date:fd.get("quote_date")||today(),p_expiry_date:fd.get("expiry_date")||null,p_subject:fd.get("subject"),p_description:fd.get("description")||fd.get("subject"),p_currency:"ZAR",p_discount_type:fd.get("discount_type")||"PERCENT",p_discount_value:Number(fd.get("discount_value")||0),p_tax_rate:Number(fd.get("tax_rate")||0),p_shipping_charge:Number(fd.get("shipping_charge")||0),p_adjustment:Number(fd.get("adjustment")||0),p_customer_notes:fd.get("customer_notes")||null,p_terms:fd.get("terms")||null,p_items:items});}this.close();await this.load();this.message("Quote saved successfully.","success");}catch(err){console.error("[QuoteController] save failed",err);this.message(err.message,"error");}}
 async approve(id){if(!this.permissions.approve_quotes)return this.message("Approval permission is required.","error");await this.request(`quotes?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify({status:"APPROVED",approved_by:auth.getCurrentUser().id,approved_at:new Date().toISOString()})});await this.load();this.message("Quote approved.","success");}
 async send(id){if(!this.permissions.approve_quotes&&!this.permissions.edit_quotes)return this.message("Quote management permission is required.","error");await this.request(`quotes?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify({status:"APPROVED",delivery_status:"SENT",sent_at:new Date().toISOString()})});await this.load();this.message("Quote marked as sent.","success");}
 async decide(id,decision,status){if(!this.permissions.edit_quotes&&!this.permissions.approve_quotes)return this.message("Quote management permission is required.","error");const patch={customer_decision:decision,status};patch[decision.toLowerCase()==="accepted"?"accepted_at":"declined_at"]=new Date().toISOString();await this.request(`quotes?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify(patch)});await this.load();this.message(`Quote ${decision.toLowerCase()}.`,"success");}
 async convert(id){if(!this.permissions.approve_quotes)return this.message("Approval permission is required to convert a quote.","error");try{const invoiceId=await this.rpc("convert_quote_to_invoice",{p_quote_id:id});await this.load();this.message(`Quote converted to invoice ${invoiceId}.`,"success");}catch(e){this.message(e.message,"error");}}
 render(){const pending=this.rows.filter(x=>String(x.customer_decision||"PENDING")==="PENDING").length;const approved=this.rows.filter(x=>String(x.status||"")==="APPROVED").length;const value=this.rows.reduce((a,x)=>a+Number(x.total??x.amount??0),0);this.set("#quote-total",this.rows.length);this.set("#quote-pending",pending);this.set("#quote-approved",approved);this.set("#quote-value",money(value));const t=document.querySelector("#quotes-table");if(!t)return;t.innerHTML=this.rows.length?this.rows.map(x=>{const s=String(x.status||"DRAFT").toUpperCase(),d=String(x.customer_decision||"PENDING").toUpperCase(),delivery=String(x.delivery_status||"NOT_SENT").replaceAll("_"," ");return `<tr><td><strong>${esc(x.quote_number||x.reference_number||"—")}</strong></td><td>${esc(this.clientName(x))}</td><td>${esc(x.subject||x.description||"—")}</td><td>${money(x.total??x.amount)}</td><td>${esc(s)}</td><td>${esc(d==="PENDING"?delivery:d)}</td><td>${esc(x.quote_date||x.created_at||"—")}</td><td class="row-actions">${this.permissions.edit_quotes?`<button class="btn btn-small" data-quote-action="edit" data-id="${x.id}">Edit</button>`:""}${this.permissions.approve_quotes&&s!=="APPROVED"&&s!=="REJECTED"?`<button class="btn btn-small btn-primary" data-quote-action="approve" data-id="${x.id}">Approve</button>`:""}${this.permissions.approve_quotes&&s==="APPROVED"&&delivery!=="SENT"?`<button class="btn btn-small" data-quote-action="send" data-id="${x.id}">Send</button>`:""}${this.permissions.edit_quotes&&delivery==="SENT"&&d==="PENDING"?`<button class="btn btn-small" data-quote-action="accept" data-id="${x.id}">Accept</button><button class="btn btn-small btn-danger" data-quote-action="decline" data-id="${x.id}">Decline</button>`:""}${this.permissions.approve_quotes&&(d==="ACCEPTED"||s==="APPROVED")?`<button class="btn btn-small btn-primary" data-quote-action="convert" data-id="${x.id}">Invoice</button>`:""}</td></tr>`;}).join(""):"<tr><td colspan=\"8\" class=\"empty-state\">No quotes found.</td></tr>";document.querySelector("[data-quote-action='new']")?.toggleAttribute("disabled",!this.permissions.create_quotes);}
 openModal(h){const x=document.querySelector("#quote-modal");if(x){x.innerHTML=h;x.hidden=false;x.querySelector("input,select,textarea")?.focus();}}
 close(){const x=document.querySelector("#quote-modal");if(x){x.hidden=true;x.innerHTML="";}}
 message(m,type="success"){const x=document.querySelector("#quote-message");if(x){x.hidden=false;x.className=`login-message ${type==="error"?"login-error":"login-success"}`;x.textContent=m;}}
 set(s,v){const x=document.querySelector(s);if(x)x.textContent=String(v);}
}
export default new QuoteController();
