import auth from "../auth/AuthService.js";
import authConfig from "../auth/auth.config.js";
import navigation from "../core/navigation.js";
import { resolveUserDashboardRole } from "./DashboardAccess.js";
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");
class QuoteController{
 constructor(){this.role=null;this.rows=[];this.permissions={};this.bound=false;this.onClick=this.onClick.bind(this);this.onSubmit=this.onSubmit.bind(this);}
 async initialise(){await auth.initialise();if(!auth.isAuthenticated())return navigation.toLogin(location.pathname,{replace:true});this.role=await resolveUserDashboardRole(auth.getCurrentUser());if(!["SUPER_ADMIN","STAFF"].includes(this.role))return navigation.toRoleDashboard(this.role,{replace:true});const keys=["view_quotes","create_quotes","edit_quotes","approve_quotes"];this.permissions=this.role==="SUPER_ADMIN"?Object.fromEntries(keys.map(k=>[k,true])):Object.fromEntries(await Promise.all(keys.map(async k=>[k,await this.permission(k)])));if(!this.permissions.view_quotes)return this.message("You do not have permission to view quotes.","error");this.bind();await this.load();}
 async request(path,options={}){const token=auth.getToken();const r=await fetch(`${authConfig.supabase.url}/rest/v1/${path}`,{...options,headers:{Accept:"application/json",apikey:authConfig.supabase.publishableKey,Authorization:`Bearer ${token}`,"Content-Type":"application/json",Prefer:"return=representation",...(options.headers||{})}});const b=await r.json().catch(()=>[]);if(!r.ok)throw new Error(b?.message||b?.details||b?.hint||`Quote request failed (${r.status}).`);return b;}
 async permission(key){try{const r=await fetch(`${authConfig.supabase.url}/rest/v1/rpc/has_staff_permission`,{method:"POST",headers:{apikey:authConfig.supabase.publishableKey,Authorization:`Bearer ${auth.getToken()}`,"Content-Type":"application/json"},body:JSON.stringify({p_permission_key:key})});return r.ok&&Boolean(await r.json());}catch{return false;}}
 bind(){if(this.bound)return;this.bound=true;document.addEventListener("click",this.onClick);document.addEventListener("submit",this.onSubmit);document.querySelector("[data-auth-action='logout']")?.addEventListener("click",async e=>{e.preventDefault();await auth.logout({remote:true,reason:"user"});navigation.toLogin(null,{replace:true});});}
 async load(){try{this.rows=await this.request("quotes?select=id,matter_id,business_id,individual_user_id,quote_number,description,amount,status,created_by,approved_by,approved_at,created_at,updated_at&order=created_at.desc");this.rows=Array.isArray(this.rows)?this.rows:[];this.render();}catch(e){this.message(e.message,"error");}}
 openForm(row={}){if(!this.permissions.create_quotes)return this.message("You do not have permission to create quotes.","error");this.openModal(`<div class="modal-backdrop" data-quote-action="close"></div><section class="modal-card"><div class="modal-header"><div><p class="eyebrow">Live Supabase</p><h2>${row.id?"Edit":"Create"} Quote</h2></div><button class="icon-button" data-quote-action="close">×</button></div><form id="quote-form" data-id="${esc(row.id||"")}"><div class="form-grid"><label>Quote number<input name="quote_number" maxlength="100" value="${esc(row.quote_number||"")}"></label><label>Amount<input name="amount" type="number" min="0" step="0.01" required value="${esc(row.amount||0)}"></label><label>Status<select name="status"><option value="DRAFT" ${row.status==="DRAFT"?"selected":""}>Draft</option><option value="PENDING" ${row.status==="PENDING"?"selected":""}>Pending</option><option value="APPROVED" ${row.status==="APPROVED"?"selected":""}>Approved</option><option value="REJECTED" ${row.status==="REJECTED"?"selected":""}>Rejected</option><option value="EXPIRED" ${row.status==="EXPIRED"?"selected":""}>Expired</option></select></label><label class="form-wide">Description<textarea name="description" rows="5" required>${esc(row.description||"")}</textarea></label></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-quote-action="close">Cancel</button><button class="btn btn-primary">${row.id?"Save Changes":"Create Quote"}</button></div></form></section>`);}
 onClick(e){const b=e.target.closest("[data-quote-action]");if(!b)return;const a=b.dataset.quoteAction;if(a==="new")return this.openForm();if(a==="edit")return this.openForm(this.rows.find(x=>x.id===b.dataset.id)||{});if(a==="approve")return this.approve(b.dataset.id);if(a==="refresh")return this.load();if(a==="close")return this.close();}
 async approve(id){if(!this.permissions.approve_quotes)return this.message("You do not have permission to approve quotes.","error");try{await this.request(`quotes?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify({status:"APPROVED",approved_by:auth.getCurrentUser().id,approved_at:new Date().toISOString()})});await this.load();this.message("Quote approved successfully.","success");}catch(e){this.message(e.message,"error");}}
 async onSubmit(e){if(e.target.id!=="quote-form")return;e.preventDefault();const f=e.target,raw=Object.fromEntries(new FormData(f).entries()),p={quote_number:String(raw.quote_number||"").trim()||null,description:String(raw.description||"").trim(),amount:Number(raw.amount||0),status:raw.status||"DRAFT"};try{if(f.dataset.id){if(!this.permissions.edit_quotes)throw new Error("You do not have permission to edit quotes.");await this.request(`quotes?id=eq.${encodeURIComponent(f.dataset.id)}`,{method:"PATCH",body:JSON.stringify(p)});}else{p.created_by=auth.getCurrentUser().id;await this.request("quotes",{method:"POST",body:JSON.stringify(p)});}this.close();await this.load();this.message("Quote saved successfully.","success");}catch(err){this.message(err.message,"error");}}
 render(){const total=this.rows.length,pending=this.rows.filter(x=>["PENDING","SUBMITTED"].includes(String(x.status||"").toUpperCase())).length,approved=this.rows.filter(x=>String(x.status||"").toUpperCase()==="APPROVED").length,value=this.rows.reduce((a,x)=>a+Number(x.amount||0),0);this.set("#quote-total",total);this.set("#quote-pending",pending);this.set("#quote-approved",approved);this.set("#quote-value",new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR"}).format(value));const t=document.querySelector("#quotes-table");if(!t)return;t.innerHTML=this.rows.length?this.rows.map(x=>`<tr><td>${esc(x.quote_number||"—")}</td><td>${esc(x.individual_user_id||x.business_id||"Unlinked")}</td><td>${esc(x.description)}</td><td>R${Number(x.amount||0).toFixed(2)}</td><td>${esc(x.status)}</td><td>${this.date(x.created_at)}</td><td class="row-actions">${this.permissions.edit_quotes?`<button class="btn btn-small" data-quote-action="edit" data-id="${x.id}">Edit</button>`:""}${this.permissions.approve_quotes&&!['APPROVED','REJECTED'].includes(String(x.status||'').toUpperCase())?`<button class="btn btn-small btn-primary" data-quote-action="approve" data-id="${x.id}">Approve</button>`:""}</td></tr>`).join(""):"<tr><td colspan=\"7\" class=\"empty-state\">No quotes found.</td></tr>";document.querySelector("[data-quote-action='new']")?.toggleAttribute("disabled",!this.permissions.create_quotes);}
 openModal(h){const x=document.querySelector("#quote-modal");if(x){x.innerHTML=h;x.hidden=false;x.querySelector("input,textarea,select")?.focus();}}
 close(){const x=document.querySelector("#quote-modal");if(x){x.hidden=true;x.innerHTML="";}}
 message(m,type){const x=document.querySelector("#quote-message");if(x){x.hidden=false;x.className=`login-message ${type==="error"?"login-error":"login-success"}`;x.textContent=m;}}
 set(s,v){const x=document.querySelector(s);if(x)x.textContent=String(v);}
 date(v){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("en-ZA",{dateStyle:"medium",timeStyle:"short"}).format(d);}
}
export default new QuoteController();
