/**
 * Super Admin Dashboard control map.
 * Keeps the existing dashboard routes but groups them by operating function.
 */
export const SUPER_ADMIN_DASHBOARD_CATEGORIES = Object.freeze([
    {
        key: "marketing",
        title: "Marketing",
        description: "Client acquisition, campaigns, performance and growth intelligence.",
        modules: [
            { title: "Analytics", href: "./analytics.html", description: "Performance, acquisition and business intelligence." },
            { title: "AI Control & Knowledge", href: "./ai.html", description: "Governed AI orchestration, knowledge and recommendations." }
        ]
    },
    {
        key: "operations",
        title: "Operations",
        description: "The live work queue that keeps matters moving through the firm.",
        modules: [
            { title: "Matters", href: "./matters.html", description: "Open, monitor and progress firm matters." },
            { title: "Assignments", href: "./assignments.html", description: "Allocate matters and operational work to active staff." },
            { title: "Cases", href: "./cases.html", description: "Manage case records linked to matters." },
            { title: "Document Vault", href: "./document-vault.html", description: "Review controlled client documents and ingestion state." }
        ]
    },
    {
        key: "intelligence",
        title: "Intelligence",
        description: "Decision support, AI workload and governed operational insight.",
        modules: [
            { title: "AI Control & Knowledge", href: "./ai.html", description: "AI orchestration, analysis and controlled knowledge operations." },
            { title: "Analytics", href: "./analytics.html", description: "Business intelligence and performance trends." },
            { title: "Reports", href: "./reports.html", description: "Operational, financial and document reporting." }
        ]
    },
    {
        key: "deals",
        title: "Deals",
        description: "Commercial workflow from quote through billing and collection.",
        modules: [
            { title: "Quotes", href: "./quotes.html", description: "Create, review and track commercial quotes." },
            { title: "Invoices", href: "./invoices.html", description: "Create, send, track and audit invoices." }
        ]
    },
    {
        key: "customers",
        title: "Customers",
        description: "Authoritative individual and business client relationships.",
        modules: [
            { title: "Individuals & Businesses", href: "./accounts.html", description: "Manage authoritative client account records." }
        ]
    },
    {
        key: "sales",
        title: "Sales",
        description: "Commercial pipeline and service conversion surfaces.",
        modules: [
            { title: "Quotes", href: "./quotes.html", description: "Manage the firm's active quotation pipeline." },
            { title: "Service Inventory & Rates", href: "./service-inventory.html", description: "Authoritative services and rates used by commercial workflows." }
        ]
    },
    {
        key: "back-office",
        title: "Back Office",
        description: "Firm configuration, people, compliance controls and administration.",
        modules: [
            { title: "Organisation Master", href: "./organisation-profile.html", description: "Legal identity, tax, banking, branding and operating terms." },
            { title: "Staff & Permissions", href: "./staff-admin.html", description: "Administer staff accounts, roles and permissions." },
            { title: "Reports", href: "./reports.html", description: "Authoritative operational and financial reporting." }
        ]
    },
    {
        key: "ai-workload",
        title: "AI Workload",
        description: "The controlled workload generated by document, matter and intelligence workers.",
        modules: [
            { title: "AI Control & Knowledge", href: "./ai.html", description: "Monitor governed AI workers, analysis and knowledge operations." },
            { title: "Document Vault", href: "./document-vault.html", description: "Monitor document ingestion and verification boundaries." }
        ]
    }
]);

export function getSuperAdminCategories() {
    return SUPER_ADMIN_DASHBOARD_CATEGORIES.map(category => ({
        ...category,
        modules: category.modules.map(module => ({ ...module }))
    }));
}

export default SUPER_ADMIN_DASHBOARD_CATEGORIES;
