const MatterStage = Object.freeze({

    ENQUIRY: "ENQUIRY",

    AI_CONSULTATION: "AI_CONSULTATION",

    DOCUMENT_COLLECTION: "DOCUMENT_COLLECTION",

    DOCUMENT_REVIEW: "DOCUMENT_REVIEW",

    BOOKING: "BOOKING",

    CONSULTATION: "CONSULTATION",

    PREPARATION: "PREPARATION",

    SUBMISSION: "SUBMISSION",

    WAITING: "WAITING",

    OUTCOME: "OUTCOME",

    COMPLETED: "COMPLETED"

});

export default MatterStage;
